var c=void 0,f=!0,h=null,j=!1;function k(a){return function(){return this[a]}}function m(a){return function(){return a}}var q,aa=this;aa.cc=f;Math.floor(2147483648*Math.random()).toString(36);function r(a,b){var d=a.split("."),e=aa;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&b!==c?e[g]=b:e=e[g]?e[g]:e[g]={}}function t(a,b){function d(){}d.prototype=b.prototype;a.f=b.prototype;a.prototype=new d;a.prototype.constructor=a};document.createElement("video");document.createElement("audio");function u(a,b,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(u.ja[a])return u.ja[a];a=u.j(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new v(a,b,d)}var ba=u;u.Ma="GENERATED_CDN_VSN";u.La="https:"==document.location.protocol?"https://":"http://";
u.options={techOrder:["html5","flash"],html5:{},flash:{sc:u.La+"vjs.zencdn.net/c/video-js.swf"},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}}};u.ja={};"GENERATED_CDN_VSN"!=u.Ma&&(ba.options.flash.swf=u.La+"vjs.zencdn.net/"+u.Ma+"/video-js.swf");u.jc={};u.d=function(a,b,d){var e=u.getData(a);e.o||(e.o={});e.o[b]||(e.o[b]=[]);d.n||(d.n=u.n++);e.o[b].push(d);e.G||(e.disabled=j,e.G=function(b){if(!e.disabled){b=u.Va(b);var d=e.o[b.type];if(d)for(var d=d.slice(0),l=0,s=d.length;l<s&&!b.bb();l++)d[l].call(a,b)}});1==e.o[b].length&&(document.addEventListener?a.addEventListener(b,e.G,j):document.attachEvent&&a.attachEvent("on"+b,e.G))};
u.m=function(a,b,d){if(u.ab(a)){var e=u.getData(a);if(e.o)if(b){var g=e.o[b];if(g){if(d){if(d.n)for(e=0;e<g.length;e++)g[e].n===d.n&&g.splice(e--,1)}else e.o[b]=[];u.Pa(a,b)}}else for(g in e.o)b=g,e.o[b]=[],u.Pa(a,b)}};u.Pa=function(a,b){var d=u.getData(a);0===d.o[b].length&&(delete d.o[b],document.removeEventListener?a.removeEventListener(b,d.G,j):document.detachEvent&&a.detachEvent("on"+b,d.G));u.Aa(d.o)&&(delete d.o,delete d.G,delete d.disabled);u.Aa(d)&&u.hb(a)};
u.Va=function(a){function b(){return f}function d(){return j}if(!a||!a.Ba){var e=a||window.event,g;for(g in e)a[g]=e[g];a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){a.returnValue=j;a.da=b};a.da=d;a.stopPropagation=function(){a.cancelBubble=f;a.Ba=b};a.Ba=d;a.stopImmediatePropagation=function(){a.bb=b;a.stopPropagation()};a.bb=d;a.clientX!=h&&(e=document.documentElement,g=document.body,a.pageX=a.clientX+(e&&
e.scrollLeft||g&&g.scrollLeft||0)-(e&&e.clientLeft||g&&g.clientLeft||0),a.pageY=a.clientY+(e&&e.scrollTop||g&&g.scrollTop||0)-(e&&e.clientTop||g&&g.clientTop||0));a.which=a.charCode||a.keyCode;a.button!=h&&(a.button=a.button&1?0:a.button&4?1:a.button&2?2:0)}return a};
u.h=function(a,b){var d=u.ab(a)?u.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof b&&(b={type:b,target:a});b=u.Va(b);d.G&&d.G.call(a,b);if(e&&!b.Ba())u.h(e,b);else if(!e&&!b.da()&&(d=u.getData(b.target),b.target[b.type])){d.disabled=f;if("function"===typeof b.target[b.type])b.target[b.type]();d.disabled=j}return!b.da()};u.B=function(a,b,d){u.d(a,b,function(){u.m(a,b,arguments.callee);d.apply(this,arguments)})};u.ic={};u.c=function(a,b){var d=document.createElement(a||"div"),e;for(e in b)b.hasOwnProperty(e)&&(d[e]=b[e]);return d};u.K=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};u.g={};u.g.toString=Object.prototype.toString;u.g.hasOwnProperty=Object.prototype.hasOwnProperty;u.g.V=function(a,b,d){for(var e in a)u.g.hasOwnProperty.call(a,e)&&b.call(d||this,e,a[e])};u.g.t=function(a,b){if(!b)return a;for(var d in b)u.g.hasOwnProperty.call(b,d)&&(a[d]=b[d]);return a};
u.g.Ua=function(a,b){var d,e,g;a=u.g.copy(a);for(d in b)u.g.hasOwnProperty.call(b,d)&&(e=a[d],g=b[d],a[d]="[object Object]"===u.g.toString.call(e)&&"[object Object]"===u.g.toString.call(g)?u.g.Ua(e,g):b[d]);return a};u.g.copy=function(a){return u.g.t({},a)};u.bind=function(a,b,d){function e(){return b.apply(a,arguments)}b.n||(b.n=u.n++);e.n=d?d+"_"+b.n:b.n;return e};u.U={};u.n=1;u.expando="vdata"+(new Date).getTime();u.getData=function(a){var b=a[u.expando];b||(b=a[u.expando]=u.n++,u.U[b]={});return u.U[b]};
u.ab=function(a){a=a[u.expando];return!(!a||u.Aa(u.U[a]))};u.hb=function(a){var b=a[u.expando];if(b){delete u.U[b];try{delete a[u.expando]}catch(d){a.removeAttribute?a.removeAttribute(u.expando):a[u.expando]=h}}};u.Aa=function(a){for(var b in a)if(a[b]!==h)return j;return f};u.q=function(a,b){-1==(" "+a.className+" ").indexOf(" "+b+" ")&&(a.className=""===a.className?b:a.className+" "+b)};
u.u=function(a,b){if(-1!=a.className.indexOf(b)){var d=a.className.split(" ");d.splice(d.indexOf(b),1);a.className=d.join(" ")}};u.vb=u.c("video");u.A=navigator.userAgent;u.tb=!!u.A.match(/iPad/i);u.sb=!!u.A.match(/iPhone/i);u.ub=!!u.A.match(/iPod/i);u.rb=u.tb||u.sb||u.ub;var ca=u,da;var ea=u.A.match(/OS (\d+)_/i);da=ea&&ea[1]?ea[1]:c;ca.dc=da;u.pb=!!u.A.match(/Android.*AppleWebKit/i);var fa=u,ga=u.A.match(/Android (\d+)\./i);fa.ob=ga&&ga[1]?ga[1]:h;u.qb=function(){return!!u.A.match("Firefox")};
u.ya=function(a){var b={};if(a&&a.attributes&&0<a.attributes.length)for(var d=a.attributes,e,g,n=d.length-1;0<=n;n--){e=d[n].name;g=d[n].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==h?f:j;b[e]=g}return b};
u.mc=function(a,b){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(b):a.currentStyle&&(b=b.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),d=a.currentStyle[b]);return d};u.za=function(a,b){b.firstChild?b.insertBefore(a,b.firstChild):b.appendChild(a)};u.Ka={};u.j=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
u.xa=function(a,b){b=b||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),n=Math.floor(b/60%60),l=Math.floor(b/3600),g=0<g||0<l?g+":":"";return g+(((g||10<=n)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};u.xb=function(){document.body.focus();document.onselectstart=m(j)};u.Zb=function(){document.onselectstart=m(f)};u.trim=function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")};u.round=function(a,b){b||(b=0);return Math.round(a*Math.pow(10,b))/Math.pow(10,b)};
u.Sa=function(a){return{length:1,start:m(0),end:function(){return a}}};
u.get=function(a,b,d){var e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});var g=new XMLHttpRequest;try{g.open("GET",a)}catch(n){d(n)}g.onreadystatechange=
function(){4===g.readyState&&(200===g.status||e&&0===g.status?b(g.responseText):d&&d())};try{g.send()}catch(l){d&&d(l)}};u.Ub=function(a){var b=window.localStorage||j;if(b)try{b.volume=a}catch(d){22==d.code||1014==d.code?u.log("LocalStorage Full (VideoJS)",d):u.log("LocalStorage Error (VideoJS)",d)}};u.Ya=function(a){a.match(/^https?:\/\//)||(a=u.c("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
u.log=function(){u.log.history=u.log.history||[];u.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};u.Db="getBoundingClientRect"in document.documentElement?function(a){var b;try{b=a.getBoundingClientRect()}catch(d){}if(!b)return 0;a=document.body;return b.left+(window.pageXOffset||a.scrollLeft)-(document.documentElement.clientLeft||a.clientLeft||0)}:function(a){for(var b=a.offsetLeft;a=a.offsetParent;)b+=a.offsetLeft;return b};function x(a,b,d){this.a=a;this.e=u.g.copy(this.e);b=this.options(b);this.H=b.id||(b.el&&b.el.id?b.el.id:a.id()+"_component_"+u.n++);this.Ib=b.name||h;this.b=b.el||this.c();this.v=[];this.sa={};this.F={};if((a=this.e)&&a.children){var e=this;u.g.V(a.children,function(a,b){b!==j&&!b.loadEvent&&(e[a]=e.I(a,b))})}y(this,d)}q=x.prototype;
q.w=function(){if(this.v)for(var a=this.v.length-1;0<=a;a--)this.v[a].w&&this.v[a].w();this.F=this.sa=this.v=h;this.m();this.b.parentNode&&this.b.parentNode.removeChild(this.b);u.hb(this.b);this.b=h};q.Ob=k("a");q.options=function(a){return a===c?this.e:this.e=u.g.Ua(this.e,a)};q.c=function(a,b){return u.c(a,b)};q.Za=k("b");q.j=k("b");q.id=k("H");q.name=k("Ib");q.children=k("v");
q.I=function(a,b){var d,e;"string"===typeof a?(e=a,b=b||{},d=b.componentClass||u.K(e),b.name=e,d=new window.videojs[d](this.a||this,b)):d=a;this.v.push(d);"function"===typeof d.id&&(this.sa[d.id()]=d);(e=e||d.name&&d.name())&&(this.F[e]=d);"function"===typeof d.j&&d.j()&&this.b.appendChild(d.j());return d};
q.removeChild=function(a){"string"===typeof a&&(a=this.F[a]);if(a&&this.v){for(var b=j,d=this.v.length-1;0<=d;d--)if(this.v[d]===a){b=f;this.v.splice(d,1);break}b&&(this.sa[a.id]=h,this.F[a.name]=h,(b=a.j())&&b.parentNode===this.b&&this.b.removeChild(a.j()))}};q.r=m("");q.d=function(a,b){u.d(this.b,a,u.bind(this,b));return this};q.m=function(a,b){u.m(this.b,a,b);return this};q.B=function(a,b){u.B(this.b,a,u.bind(this,b));return this};q.h=function(a,b){u.h(this.b,a,b);return this};
function y(a,b){b&&(a.Q?b.call(a):(a.ma===c&&(a.ma=[]),a.ma.push(b)))}function ha(a){a.Q=f;var b=a.ma;if(b&&0<b.length){for(var d=0,e=b.length;d<e;d++)b[d].call(a);a.ma=[];a.h("ready")}}q.q=function(a){u.q(this.b,a);return this};q.u=function(a){u.u(this.b,a);return this};q.show=function(){this.b.style.display="block";return this};q.s=function(){this.b.style.display="none";return this};q.ca=function(){this.u("vjs-fade-out");this.q("vjs-fade-in");return this};
q.va=function(){this.u("vjs-fade-in");this.q("vjs-fade-out");return this};q.cb=function(){var a=this.b.style;a.display="block";a.opacity=1;a.ac="visible";return this};function ia(a){a=a.b.style;a.display="";a.opacity="";a.ac=""}q.width=function(a,b){return ja(this,"width",a,b)};q.height=function(a,b){return ja(this,"height",a,b)};q.Ab=function(a,b){return this.width(a,f).height(b)};
function ja(a,b,d,e){if(d!==c)return a.b.style[b]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:d+"px",e||a.h("resize"),a;if(!a.b)return 0;d=a.b.style[b];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.b["offset"+u.K(b)],10)};function v(a,b,d){this.D=a;b=u.g.t(ka(a),b);this.l={};x.call(this,this,b,d);this.fb=this.e.poster;this.Qa=this.e.controls;this.B("play",function(a){u.h(this.b,{type:"firstplay",target:this.b})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())});this.d("ended",this.Kb);this.d("play",this.Ia);this.d("firstplay",this.Lb);this.d("pause",this.Ha);this.d("progress",this.Mb);this.d("durationchange",this.Jb);this.d("error",this.Fa);u.ja[this.H]=this;b.plugins&&u.g.V(b.plugins,function(a,
b){this[a](b)},this)}t(v,x);q=v.prototype;q.e=u.options;q.w=function(){u.ja[this.H]=h;this.D&&this.D.player&&(this.D.player=h);this.b&&this.b.player&&(this.b.player=h);clearInterval(this.la);this.Z();this.i&&this.i.w();v.f.w.call(this)};function ka(a){var b={sources:[],tracks:[]};u.g.t(b,u.ya(a));if(a.hasChildNodes())for(var d,e=a.childNodes,g=0,n=e.length;g<n;g++)a=e[g],d=a.nodeName.toLowerCase(),"source"===d?b.sources.push(u.ya(a)):"track"===d&&b.tracks.push(u.ya(a));return b}q.Za=k("b");
q.c=function(){var a=this.b=v.f.c.call(this,"div"),b=this.D;b.removeAttribute("controls");b.removeAttribute("poster");b.removeAttribute("width");b.removeAttribute("height");if(b.hasChildNodes())for(var d=b.childNodes.length,e=0,g=b.childNodes;e<d;e++)("source"==g[0].nodeName.toLowerCase()||"track"==g[0].nodeName.toLowerCase())&&b.removeChild(g[0]);b.id=b.id||"vjs_video_"+u.n++;a.id=b.id;a.className=b.className;b.id+="_html5_api";b.className="vjs-tech";b.player=a.player=this;this.q("vjs-paused");this.width(this.e.width,
f);this.height(this.e.height,f);b.parentNode&&b.parentNode.insertBefore(a,b);u.za(b,a);return a};
function la(a,b,d){a.i?ma(a):"Html5"!==b&&a.D&&(a.b.removeChild(a.D),a.D=h);a.M=b;a.Q=j;var e=u.g.t({source:d,qc:a.b},a.e[b.toLowerCase()]);d&&(d.src==a.l.src&&0<a.l.currentTime&&(e.startTime=a.l.currentTime),a.l.src=d.src);a.i=new window.videojs[b](a,e);y(a.i,function(){ha(this.a);if(!this.C.gb){var a=this.a;a.Da=f;a.la=setInterval(u.bind(a,function(){this.l.ra<this.buffered().end(0)?this.h("progress"):1==na(this)&&(clearInterval(this.la),this.h("progress"))}),500);a.i.B("progress",function(){this.C.gb=
f;var a=this.a;a.Da=j;clearInterval(a.la)})}this.C.mb||(a=this.a,a.Ea=f,a.d("play",a.nb),a.d("pause",a.Z),a.i.B("timeupdate",function(){this.C.mb=f;oa(this.a)}))})}function ma(a){a.i.w();a.Da&&(a.Da=j,clearInterval(a.la));a.Ea&&oa(a);a.i=j}function oa(a){a.Ea=j;a.Z();a.m("play",a.nb);a.m("pause",a.Z)}q.nb=function(){this.Ta&&this.Z();this.Ta=setInterval(u.bind(this,function(){this.h("timeupdate")}),250)};q.Z=function(){clearInterval(this.Ta)};q.Kb=function(){this.e.loop&&(this.currentTime(0),this.play())};
q.Ia=function(){u.u(this.b,"vjs-paused");u.q(this.b,"vjs-playing")};q.Lb=function(){this.e.starttime&&this.currentTime(this.e.starttime)};q.Ha=function(){u.u(this.b,"vjs-playing");u.q(this.b,"vjs-paused")};q.Mb=function(){1==na(this)&&this.h("loadedalldata")};q.Jb=function(){this.duration(z(this,"duration"))};q.Fa=function(a){u.log("Video Error",a)};function A(a,b,d){if(a.i&&a.i.Q)y(a.i,function(){this[b](d)});else try{a.i[b](d)}catch(e){u.log(e)}}
function z(a,b){if(a.i.Q)try{return a.i[b]()}catch(d){if(a.i[b]===c)u.log("Video.js: "+b+" method not defined for "+a.M+" playback technology.",d);else{if("TypeError"==d.name)throw u.log("Video.js: "+b+" unavailable on "+a.M+" playback technology element.",d),a.i.Q=j,d;u.log(d)}}}q.play=function(){var a={type:"play",target:this.b};this.h(a);a.da()||A(this,"play");return this};q.pause=function(){A(this,"pause");return this};q.paused=function(){return z(this,"paused")===j?j:f};
q.currentTime=function(a){return a!==c?(this.l.oc=a,A(this,"setCurrentTime",a),this.Ea&&this.h("timeupdate"),this):this.l.currentTime=z(this,"currentTime")||0};q.duration=function(a){return a!==c?(this.l.duration=parseFloat(a),this):this.l.duration};q.buffered=function(){var a=z(this,"buffered"),b=this.l.ra=this.l.ra||0;a&&(0<a.length&&a.end(0)!==b)&&(b=a.end(0),this.l.ra=b);return u.Sa(b)};function na(a){return a.duration()?a.buffered().end(0)/a.duration():0}
q.volume=function(a){if(a!==c)return a=Math.max(0,Math.min(1,parseFloat(a))),this.l.volume=a,A(this,"setVolume",a),u.Ub(a),this;a=parseFloat(z(this,"volume"));return isNaN(a)?1:a};q.muted=function(a){return a!==c?(A(this,"setMuted",a),this):z(this,"muted")||j};q.oa=function(){return z(this,"supportsFullScreen")||j};
q.na=function(){var a=u.Ka.na;this.L=f;a?(u.d(document,a.P,u.bind(this,function(){this.L=document[a.L];this.L===j&&u.m(document,a.P,arguments.callee);this.h("fullscreenchange")})),this.i.C.Xa===j&&this.e.flash.iFrameMode!==f&&(this.pause(),ma(this),u.d(document,a.P,u.bind(this,function(){u.m(document,a.P,arguments.callee);la(this,this.M,{src:this.l.src})}))),this.b[a.Qb]()):this.i.oa()?(this.h("fullscreenchange"),A(this,"enterFullScreen")):(this.h("fullscreenchange"),this.Fb=f,this.Bb=document.documentElement.style.overflow,
u.d(document,"keydown",u.bind(this,this.Wa)),document.documentElement.style.overflow="hidden",u.q(document.body,"vjs-full-window"),u.q(this.b,"vjs-fullscreen"),this.h("enterFullWindow"));return this};function pa(a){var b=u.Ka.na;a.L=j;b?(a.i.C.Xa===j&&a.e.flash.iFrameMode!==f&&(a.pause(),ma(a),u.d(document,b.P,u.bind(a,function(){u.m(document,b.P,arguments.callee);la(this,this.M,{src:this.l.src})}))),document[b.yb]()):(a.i.oa()?A(a,"exitFullScreen"):qa(a),a.h("fullscreenchange"))}
q.Wa=function(a){27===a.keyCode&&(this.L===f?pa(this):qa(this))};function qa(a){a.Fb=j;u.m(document,"keydown",a.Wa);document.documentElement.style.overflow=a.Bb;u.u(document.body,"vjs-full-window");u.u(a.b,"vjs-fullscreen");a.h("exitFullWindow")}
q.src=function(a){if(a instanceof Array){var b;a:{b=a;for(var d=0,e=this.e.techOrder;d<e.length;d++){var g=u.K(e[d]),n=window.videojs[g];if(n.isSupported())for(var l=0,s=b;l<s.length;l++){var p=s[l];if(n.canPlaySource(p)){b={source:p,i:g};break a}}}b=j}b?(a=b.source,b=b.i,b==this.M?this.src(a):la(this,b,a)):this.b.appendChild(u.c("p",{innerHTML:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://www.google.com/chrome">Google Chrome</a> or download the latest <a href="http://get.adobe.com/flashplayer/">Adobe Flash Player</a>.'}))}else a instanceof
Object?window.videojs[this.M].canPlaySource(a)?this.src(a.src):this.src([a]):(this.l.src=a,this.Q?(A(this,"src",a),"auto"==this.e.preload&&this.load(),this.e.autoplay&&this.play()):y(this,function(){this.src(a)}));return this};q.load=function(){A(this,"load");return this};q.currentSrc=function(){return z(this,"currentSrc")||this.l.src||""};q.ka=function(a){return a!==c?(A(this,"setPreload",a),this.e.preload=a,this):z(this,"preload")};
q.autoplay=function(a){return a!==c?(A(this,"setAutoplay",a),this.e.autoplay=a,this):z(this,"autoplay")};q.loop=function(a){return a!==c?(A(this,"setLoop",a),this.e.loop=a,this):z(this,"loop")};q.poster=function(a){a!==c&&(this.fb=a);return this.fb};q.controls=function(a){a!==c&&(this.Qa=a);return this.Qa};q.error=function(){return z(this,"error")};var ra,sa,ta,ua;
if(document.gc!==c)ra="requestFullscreen",sa="exitFullscreen",ta="fullscreenchange",ua="fullScreen";else for(var va=["moz","webkit"],wa=va.length-1;0<=wa;wa--){var B=va[wa];if(("moz"!=B||document.mozFullScreenEnabled)&&document[B+"CancelFullScreen"]!==c)ra=B+"RequestFullScreen",sa=B+"CancelFullScreen",ta=B+"fullscreenchange",ua="webkit"==B?B+"IsFullScreen":B+"FullScreen"}ra&&(u.Ka.na={Qb:ra,yb:sa,P:ta,L:ua});
function xa(a,b,d){x.call(this,a,b,d);if(!a.e.sources||0===a.e.sources.length){b=0;for(d=a.e.techOrder;b<d.length;b++){var e=u.K(d[b]),g=window.videojs[e];if(g&&g.isSupported()){la(a,e);break}}}else a.src(a.e.sources)}t(xa,x);function C(a,b){x.call(this,a,b)}t(C,x);C.prototype.r=function(){return"vjs-control "+C.f.r.call(this)};function D(a,b){x.call(this,a,b);a.B("play",u.bind(this,function(){this.ca();this.a.d("mouseover",u.bind(this,this.ca));this.a.d("mouseout",u.bind(this,this.va))}))}t(D,x);q=D.prototype;q.e={pc:"play",children:{playToggle:{},fullscreenToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},progressControl:{},volumeControl:{},muteToggle:{}}};
q.c=function(){return u.c("div",{className:"vjs-control-bar"})};q.ca=function(){D.f.ca.call(this);this.a.h("controlsvisible")};q.va=function(){D.f.va.call(this);this.a.h("controlshidden")};q.cb=function(){this.b.style.opacity="1"};function E(a,b){x.call(this,a,b);this.d("click",this.k);this.d("focus",this.ga);this.d("blur",this.fa)}t(E,C);q=E.prototype;
q.c=function(a,b){b=u.g.t({className:this.r(),innerHTML:'<div><span class="vjs-control-text">'+(this.J||"Need Text")+"</span></div>",Rb:"button",tabIndex:0},b);return E.f.c.call(this,a,b)};q.k=function(){};q.ga=function(){u.d(document,"keyup",u.bind(this,this.Y))};q.Y=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.k()};q.fa=function(){u.m(document,"keyup",u.bind(this,this.Y))};function F(a,b){E.call(this,a,b)}t(F,E);F.prototype.J="Play";
F.prototype.r=function(){return"vjs-play-button "+F.f.r.call(this)};F.prototype.k=function(){this.a.play()};function G(a,b){E.call(this,a,b)}t(G,E);G.prototype.J="Play";G.prototype.r=function(){return"vjs-pause-button "+G.f.r.call(this)};G.prototype.k=function(){this.a.pause()};function ya(a,b){E.call(this,a,b);a.d("play",u.bind(this,this.Ia));a.d("pause",u.bind(this,this.Ha))}t(ya,E);q=ya.prototype;q.J="Play";q.r=function(){return"vjs-play-control "+ya.f.r.call(this)};
q.k=function(){this.a.paused()?this.a.play():this.a.pause()};q.Ia=function(){u.u(this.b,"vjs-paused");u.q(this.b,"vjs-playing")};q.Ha=function(){u.u(this.b,"vjs-playing");u.q(this.b,"vjs-paused")};function H(a,b){E.call(this,a,b)}t(H,E);H.prototype.J="Fullscreen";H.prototype.r=function(){return"vjs-fullscreen-control "+H.f.r.call(this)};H.prototype.k=function(){this.a.L?pa(this.a):this.a.na()};function I(a,b){E.call(this,a,b);a.d("play",u.bind(this,this.s))}t(I,E);
I.prototype.c=function(){return I.f.c.call(this,"div",{className:"vjs-big-play-button",innerHTML:"<span></span>"})};I.prototype.k=function(){this.a.currentTime()&&this.a.currentTime(0);this.a.play()};
function J(a,b){x.call(this,a,b);a.d("canplay",u.bind(this,this.s));a.d("canplaythrough",u.bind(this,this.s));a.d("playing",u.bind(this,this.s));a.d("seeked",u.bind(this,this.s));a.d("seeking",u.bind(this,this.show));a.d("seeked",u.bind(this,this.s));a.d("error",u.bind(this,this.show));a.d("waiting",u.bind(this,this.show))}t(J,x);
J.prototype.c=function(){var a,b;"string"==typeof this.a.j().style.WebkitBorderRadius||"string"==typeof this.a.j().style.MozBorderRadius||"string"==typeof this.a.j().style.ec||"string"==typeof this.a.j().style.fc?(a="vjs-loading-spinner",b='<div class="ball1"></div><div class="ball2"></div><div class="ball3"></div><div class="ball4"></div><div class="ball5"></div><div class="ball6"></div><div class="ball7"></div><div class="ball8"></div>'):(a="vjs-loading-spinner-fallback",b="");return J.f.c.call(this,
"div",{className:a,innerHTML:b})};function K(a,b){x.call(this,a,b);a.d("timeupdate",u.bind(this,this.aa))}t(K,x);K.prototype.c=function(){var a=K.f.c.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.content=u.c("div",{className:"vjs-current-time-display",innerHTML:"0:00"});a.appendChild(u.c("div").appendChild(this.content));return a};K.prototype.aa=function(){var a=this.a.ib?this.a.l.currentTime:this.a.currentTime();this.content.innerHTML=u.xa(a,this.a.duration())};
function L(a,b){x.call(this,a,b);a.d("timeupdate",u.bind(this,this.aa))}t(L,x);L.prototype.c=function(){var a=L.f.c.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.content=u.c("div",{className:"vjs-duration-display",innerHTML:"0:00"});a.appendChild(u.c("div").appendChild(this.content));return a};L.prototype.aa=function(){this.a.duration()&&(this.content.innerHTML=u.xa(this.a.duration()))};function za(a,b){x.call(this,a,b)}t(za,x);
za.prototype.c=function(){return za.f.c.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};function M(a,b){x.call(this,a,b);a.d("timeupdate",u.bind(this,this.aa))}t(M,x);M.prototype.c=function(){var a=M.f.c.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.content=u.c("div",{className:"vjs-remaining-time-display",innerHTML:"-0:00"});a.appendChild(u.c("div").appendChild(this.content));return a};
M.prototype.aa=function(){this.a.duration()&&(this.content.innerHTML="-"+u.xa(this.a.duration()-this.a.currentTime()))};function N(a,b){x.call(this,a,b);this.wb=this.F[this.e.barName];this.handle=this.F[this.e.handleName];a.d(this.eb,u.bind(this,this.update));this.d("mousedown",this.Ga);this.d("focus",this.ga);this.d("blur",this.fa);this.a.d("controlsvisible",u.bind(this,this.update));y(a,u.bind(this,this.update))}t(N,x);q=N.prototype;
q.c=function(a,b){b=u.g.t({Rb:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},b);return N.f.c.call(this,a,b)};q.Ga=function(a){a.preventDefault();u.xb();u.d(document,"mousemove",u.bind(this,this.ha));u.d(document,"mouseup",u.bind(this,this.ia));this.ha(a)};q.ia=function(){u.Zb();u.m(document,"mousemove",this.ha,j);u.m(document,"mouseup",this.ia,j);this.update()};
q.update=function(){var a,b=this.$a(),d=this.handle,e=this.wb;isNaN(b)&&(b=0);a=b;if(d){a=this.b.offsetWidth;var g=d.j().offsetWidth;a=g?g/a:0;b*=1-a;a=b+a/2;d.j().style.left=u.round(100*b,2)+"%"}e.j().style.width=u.round(100*a,2)+"%"};function Aa(a,b){var d=a.b,e=u.Db(d),d=d.offsetWidth,g=a.handle;g&&(g=g.j().offsetWidth,e+=g/2,d-=g);return Math.max(0,Math.min(1,(b.pageX-e)/d))}q.ga=function(){u.d(document,"keyup",u.bind(this,this.Y))};
q.Y=function(a){37==a.which?(a.preventDefault(),this.kb()):39==a.which&&(a.preventDefault(),this.lb())};q.fa=function(){u.m(document,"keyup",u.bind(this,this.Y))};function O(a,b){x.call(this,a,b)}t(O,x);O.prototype.e={children:{seekBar:{}}};O.prototype.c=function(){return O.f.c.call(this,"div",{className:"vjs-progress-control vjs-control"})};function P(a,b){N.call(this,a,b)}t(P,N);q=P.prototype;q.e={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};
q.eb="timeupdate";q.c=function(){return P.f.c.call(this,"div",{className:"vjs-progress-holder"})};q.$a=function(){return this.a.currentTime()/this.a.duration()};q.Ga=function(a){P.f.Ga.call(this,a);this.a.ib=f;this.$b=!this.a.paused();this.a.pause()};q.ha=function(a){a=Aa(this,a)*this.a.duration();a==this.a.duration()&&(a-=0.1);this.a.currentTime(a)};q.ia=function(a){P.f.ia.call(this,a);this.a.ib=j;this.$b&&this.a.play()};q.lb=function(){this.a.currentTime(this.a.currentTime()+1)};
q.kb=function(){this.a.currentTime(this.a.currentTime()-1)};function Ba(a,b){x.call(this,a,b);a.d("progress",u.bind(this,this.update))}t(Ba,x);Ba.prototype.c=function(){return Ba.f.c.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};Ba.prototype.update=function(){this.b.style&&(this.b.style.width=u.round(100*na(this.a),2)+"%")};function Ca(a,b){x.call(this,a,b)}t(Ca,x);
Ca.prototype.c=function(){return Ca.f.c.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};function Da(a,b){x.call(this,a,b)}t(Da,x);Da.prototype.c=function(){return Da.f.c.call(this,"div",{className:"vjs-seek-handle",innerHTML:'<span class="vjs-control-text">00:00</span>'})};function Ea(a,b){x.call(this,a,b)}t(Ea,x);Ea.prototype.e={children:{volumeBar:{}}};Ea.prototype.c=function(){return Ea.f.c.call(this,"div",{className:"vjs-volume-control vjs-control"})};
function Fa(a,b){N.call(this,a,b)}t(Fa,N);q=Fa.prototype;q.e={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};q.eb="volumechange";q.c=function(){return Fa.f.c.call(this,"div",{className:"vjs-volume-bar"})};q.ha=function(a){this.a.volume(Aa(this,a))};q.$a=function(){return this.a.volume()};q.lb=function(){this.a.volume(this.a.volume()+0.1)};q.kb=function(){this.a.volume(this.a.volume()-0.1)};function Ga(a,b){x.call(this,a,b)}t(Ga,x);
Ga.prototype.c=function(){return Ga.f.c.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};function Ha(a,b){x.call(this,a,b)}t(Ha,x);Ha.prototype.c=function(){return Ha.f.c.call(this,"div",{className:"vjs-volume-handle",innerHTML:'<span class="vjs-control-text"></span>'})};function Q(a,b){E.call(this,a,b);a.d("volumechange",u.bind(this,this.update))}t(Q,E);
Q.prototype.c=function(){return Q.f.c.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};Q.prototype.k=function(){this.a.muted(this.a.muted()?j:f)};Q.prototype.update=function(){var a=this.a.volume(),b=3;0===a||this.a.muted()?b=0:0.33>a?b=1:0.67>a&&(b=2);for(a=0;4>a;a++)u.u(this.b,"vjs-vol-"+a);u.q(this.b,"vjs-vol-"+b)};function Ia(a,b){E.call(this,a,b);a.poster()||this.s();a.d("play",u.bind(this,this.s))}t(Ia,E);
Ia.prototype.c=function(){var a=u.c("img",{className:"vjs-poster",tabIndex:-1});this.a.poster()&&(a.src=this.a.poster());return a};Ia.prototype.k=function(){this.a.play()};function R(a,b){x.call(this,a,b)}t(R,x);function Ja(a,b){a.I(b);b.d("click",u.bind(a,function(){ia(this)}))}R.prototype.c=function(){return R.f.c.call(this,"ul",{className:"vjs-menu"})};function S(a,b){E.call(this,a,b);b.selected&&this.q("vjs-selected")}t(S,E);
S.prototype.c=function(a,b){return S.f.c.call(this,"li",u.g.t({className:"vjs-menu-item",innerHTML:this.e.label},b))};S.prototype.k=function(){this.selected(f)};S.prototype.selected=function(a){a?this.q("vjs-selected"):this.u("vjs-selected")};function T(a,b,d){x.call(this,a,b,d)}t(T,x);T.prototype.k=function(){this.a.controls()&&(this.a.paused()?this.a.play():this.a.pause())};u.media={};u.media.pa="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function Ka(){var a=u.media.pa[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=u.media.pa.length-1;0<=i;i--)T.prototype[u.media.pa[i]]=Ka();function U(a,b,d){x.call(this,a,b,d);(b=b.source)&&this.b.currentSrc==b.src?a.h("loadstart"):b&&(this.b.src=b.src);y(a,function(){this.e.autoplay&&this.paused()&&(this.D.poster=h,this.play())});this.d("click",this.k);for(a=La.length-1;0<=a;a--)u.d(this.b,La[a],u.bind(this.a,this.Cb));ha(this)}t(U,T);q=U.prototype;q.w=function(){U.f.w.call(this)};
q.c=function(){var a=this.a,b=a.D;if(!b||this.C.Hb===j)b&&a.j().removeChild(b),b=u.createElement("video",{id:b.id||a.id()+"_html5_api",className:b.className||"vjs-tech"}),u.za(b,a.j());for(var d=["autoplay","preload","loop","muted"],e=d.length-1;0<=e;e--){var g=d[e];a.e[g]!==h&&(b[g]=a.e[g])}return b};q.Cb=function(a){"play"!==a.type&&(this.h(a),a.stopPropagation())};q.play=function(){this.b.play()};q.pause=function(){this.b.pause()};q.paused=function(){return this.b.paused};q.currentTime=function(){return this.b.currentTime};
q.Tb=function(a){try{this.b.currentTime=a}catch(b){u.log(b,"Video is not ready. (Video.js)")}};q.duration=function(){return this.b.duration||0};q.buffered=function(){return this.b.buffered};q.volume=function(){return this.b.volume};q.Yb=function(a){this.b.volume=a};q.muted=function(){return this.b.muted};q.Wb=function(a){this.b.muted=a};q.width=function(){return this.b.offsetWidth};q.height=function(){return this.b.offsetHeight};
q.oa=function(){return"function"==typeof this.b.webkitEnterFullScreen&&!navigator.userAgent.match("Chrome")&&!navigator.userAgent.match("Mac OS X 10.5")?f:j};q.src=function(a){this.b.src=a};q.load=function(){this.b.load()};q.currentSrc=function(){return this.b.currentSrc};q.ka=function(){return this.b.ka};q.Xb=function(a){this.b.ka=a};q.autoplay=function(){return this.b.autoplay};q.Sb=function(a){this.b.autoplay=a};q.loop=function(){return this.b.loop};q.Vb=function(a){this.b.loop=a};q.error=function(){return this.b.error};
var La="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");U.prototype.C={kc:u.vb.webkitEnterFullScreen?!u.A.match("Chrome")&&!u.A.match("Mac OS X 10.5")?f:j:j,Hb:!u.rb};u.pb&&3>u.ob&&(document.createElement("video").constructor.prototype.canPlayType=function(a){return a&&-1!=a.toLowerCase().indexOf("video/mp4")?"maybe":""});function V(a,b,d){x.call(this,a,b,d);var e=b.source,g=b.parentEl;d=this.b=u.c("div",{id:a.id()+"_temp_flash"});var n=a.id()+"_flash_api";a=a.e;var l=u.g.t({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.ka,loop:a.loop,muted:a.muted},b.flashVars),s=u.g.t({wmode:"opaque",bgcolor:"#000000"},b.params),p=u.g.t({id:n,name:n,"class":"vjs-tech"},b.attributes);e&&(l.src=encodeURIComponent(u.Ya(e.src)));
u.za(d,g);b.startTime&&y(this,function(){this.load();this.play();this.currentTime(b.startTime)});if(b.iFrameMode===f&&!u.qb){var w=u.c("iframe",{id:n+"_iframe",name:n+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});l.readyFunction="ready";l.eventProxyFunction="events";l.errorEventProxyFunction="errors";u.d(w,"load",u.bind(this,function(){var a,d=w.contentWindow;a=w.contentDocument?w.contentDocument:w.contentWindow.document;a.write(Ma(b.swf,l,s,p));d.player=
this.a;d.ready=u.bind(this.a,function(b){b=a.getElementById(b);var d=this.i;d.b=b;u.d(b,"click",d.bind(d.k));Na(d)});d.events=u.bind(this.a,function(a,b){this&&"flash"===this.M&&this.h(b)});d.errors=u.bind(this.a,function(a,b){u.log("Flash Error",b)})}));d.parentNode.replaceChild(w,d)}else{a=Ma(b.swf,l,s,p);a=u.c("div",{innerHTML:a}).childNodes[0];e=d.parentNode;d.parentNode.replaceChild(a,d);var eb=e.childNodes[0];setTimeout(function(){eb.style.display="block"},1E3)}}t(V,T);q=V.prototype;q.w=function(){V.f.w.call(this)};
q.play=function(){this.b.vjs_play()};q.pause=function(){this.b.vjs_pause()};q.src=function(a){a=u.Ya(a);this.b.vjs_src(a);if(this.a.autoplay()){var b=this;setTimeout(function(){b.play()},0)}};q.load=function(){this.b.vjs_load()};q.poster=function(){this.b.vjs_getProperty("poster")};q.buffered=function(){return u.Sa(this.b.vjs_getProperty("buffered"))};q.oa=m(j);
var Oa=V.prototype,Pa="preload currentTime defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),Qa="error currentSrc networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");function Ra(){var a=Pa[W],b=a.charAt(0).toUpperCase()+a.slice(1);Oa["set"+b]=function(b){return this.b.vjs_setProperty(a,b)}}
function Sa(a){Oa[a]=function(){return this.b.vjs_getProperty(a)}}var W;for(W=0;W<Pa.length;W++)Sa(Pa[W]),Ra();for(W=0;W<Qa.length;W++)Sa(Qa[W]);V.prototype.C={Eb:{"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"},gb:j,mb:j,Xa:j,rc:!u.A.match("Firefox")};V.onReady=function(a){a=u.j(a);var b=a.player||a.parentNode.player,d=b.i;a.player=b;d.b=a;d.d("click",d.k);Na(d)};function Na(a){a.j().vjs_getProperty?ha(a):setTimeout(function(){Na(a)},50)}
V.onEvent=function(a,b){"play"!==b&&u.j(a).player.h(b)};V.onError=function(a,b){u.j(a).player.h("error");u.log("Flash Error",b,a)};
function Ma(a,b,d,e){var g="",n="",l="";b&&u.g.V(b,function(a,b){g+=a+"="+b+"&amp;"});d=u.g.t({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);u.g.V(d,function(a,b){n+='<param name="'+a+'" value="'+b+'" />'});e=u.g.t({data:a,width:"100%",height:"100%"},e);u.g.V(e,function(a,b){l+=a+'="'+b+'" '});return'<object type="application/x-shockwave-flash"'+l+">"+n+"</object>"};function X(a){a.$=a.$||[];return a.$}function Ta(a,b,d){for(var e=a.$,g=0,n=e.length,l,s;g<n;g++)l=e[g],l.id()===b?(l.show(),s=l):d&&(l.z()==d&&0<l.mode())&&l.disable();(b=s?s.z():d?d:j)&&a.h(b+"trackchange")}function Y(a,b){x.call(this,a,b);this.H=b.id||"vjs_"+b.kind+"_"+b.language+"_"+u.n++;this.jb=b.src;this.zb=b["default"]||b.dflt;this.tc=b.title;this.nc=b.srclang;this.Gb=b.label;this.O=[];this.Na=[];this.S=this.T=0}t(Y,x);q=Y.prototype;q.z=k("p");q.src=k("jb");q.ua=k("zb");q.label=k("Gb");
q.readyState=k("T");q.mode=k("S");q.c=function(){return Y.f.c.call(this,"div",{className:"vjs-"+this.p+" vjs-text-track"})};q.show=function(){Ua(this);this.S=2;Y.f.show.call(this)};q.s=function(){Ua(this);this.S=1;Y.f.s.call(this)};q.disable=function(){2==this.S&&this.s();this.a.m("timeupdate",u.bind(this,this.update,this.H));this.a.m("ended",u.bind(this,this.reset,this.H));this.reset();this.a.F.textTrackDisplay.removeChild(this);this.S=0};
function Ua(a){0===a.T&&a.load();0===a.S&&(a.a.d("timeupdate",u.bind(a,a.update,a.H)),a.a.d("ended",u.bind(a,a.reset,a.H)),("captions"===a.p||"subtitles"===a.p)&&a.a.F.textTrackDisplay.I(a))}q.load=function(){0===this.T&&(this.T=1,u.get(this.jb,u.bind(this,this.Nb),u.bind(this,this.Fa)))};q.Fa=function(a){this.error=a;this.T=3;this.h("error")};
q.Nb=function(a){var b,d;a=a.split("\n");for(var e="",g=1,n=a.length;g<n;g++)if(e=u.trim(a[g])){-1==e.indexOf("--\x3e")?(b=e,e=u.trim(a[++g])):b=this.O.length;b={id:b,index:this.O.length};d=e.split(" --\x3e ");b.startTime=Va(d[0]);b.W=Va(d[1]);for(d=[];a[++g]&&(e=u.trim(a[g]));)d.push(e);b.text=d.join("<br/>");this.O.push(b)}this.T=2;this.h("loaded")};
function Va(a){var b=a.split(":");a=0;var d,e,g;3==b.length?(d=b[0],e=b[1],b=b[2]):(d=0,e=b[0],b=b[1]);b=b.split(/\s+/);b=b.splice(0,1)[0];b=b.split(/\.|,/);g=parseFloat(b[1]);b=b[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(b);g&&(a+=g/1E3);return a}
q.update=function(){if(0<this.O.length){var a=this.a.currentTime();if(this.Ja===c||a<this.Ja||this.ea<=a){var b=this.O,d=this.a.duration(),e=0,g=j,n=[],l,s,p,w;a>=this.ea||this.ea===c?w=this.wa!==c?this.wa:0:(g=f,w=this.Ca!==c?this.Ca:b.length-1);for(;;){p=b[w];if(p.W<=a)e=Math.max(e,p.W),p.ba&&(p.ba=j);else if(a<p.startTime){if(d=Math.min(d,p.startTime),p.ba&&(p.ba=j),!g)break}else g?(n.splice(0,0,p),s===c&&(s=w),l=w):(n.push(p),l===c&&(l=w),s=w),d=Math.min(d,p.W),e=Math.max(e,p.startTime),p.ba=
f;if(g)if(0===w)break;else w--;else if(w===b.length-1)break;else w++}this.Na=n;this.ea=d;this.Ja=e;this.wa=l;this.Ca=s;a=this.Na;b="";d=0;for(e=a.length;d<e;d++)b+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.b.innerHTML=b;this.h("cuechange")}}};q.reset=function(){this.ea=0;this.Ja=this.a.duration();this.Ca=this.wa=0};function Wa(a,b){Y.call(this,a,b)}t(Wa,Y);Wa.prototype.p="captions";function Xa(a,b){Y.call(this,a,b)}t(Xa,Y);Xa.prototype.p="subtitles";function Ya(a,b){Y.call(this,a,b)}
t(Ya,Y);Ya.prototype.p="chapters";function Za(a,b,d){x.call(this,a,b,d);if(a.e.tracks&&0<a.e.tracks.length){b=this.a;a=a.e.tracks;var e;for(d=0;d<a.length;d++){e=a[d];var g=b,n=e.kind,l=e.label,s=e.language,p=e;e=g.$=g.$||[];p=p||{};p.kind=n;p.label=l;p.language=s;n=u.K(n||"subtitles");g=new window.videojs[n+"Track"](g,p);e.push(g)}}}t(Za,x);Za.prototype.c=function(){return Za.f.c.call(this,"div",{className:"vjs-text-track-display"})};
function Z(a,b){var d=this.N=b.track;b.label=d.label();b.selected=d.ua();S.call(this,a,b);this.a.d(d.z()+"trackchange",u.bind(this,this.update))}t(Z,S);Z.prototype.k=function(){Z.f.k.call(this);Ta(this.a,this.N.id(),this.N.z())};Z.prototype.update=function(){2==this.N.mode()?this.selected(f):this.selected(j)};function $a(a,b){b.track={z:function(){return b.kind},Ob:a,label:m("Off"),ua:m(j),mode:m(j)};Z.call(this,a,b)}t($a,Z);$a.prototype.k=function(){$a.f.k.call(this);Ta(this.a,this.N.id(),this.N.z())};
$a.prototype.update=function(){for(var a=X(this.a),b=0,d=a.length,e,g=f;b<d;b++)e=a[b],e.z()==this.N.z()&&2==e.mode()&&(g=j);g?this.selected(f):this.selected(j)};function $(a,b){E.call(this,a,b);this.R=this.ta();0===this.X.length&&this.s()}t($,E);q=$.prototype;q.ta=function(){var a=new R(this.a);a.j().appendChild(u.c("li",{className:"vjs-menu-title",innerHTML:u.K(this.p)}));Ja(a,new $a(this.a,{kind:this.p}));this.X=this.Ra();for(var b=0;b<this.X.length;b++)Ja(a,this.X[b]);this.I(a);return a};
q.Ra=function(){for(var a=[],b,d=0;d<X(this.a).length;d++)b=X(this.a)[d],b.z()===this.p&&a.push(new Z(this.a,{track:b}));return a};q.r=function(){return this.className+" vjs-menu-button "+$.f.r.call(this)};q.ga=function(){this.R.cb();u.B(this.R.b.childNodes[this.R.b.childNodes.length-1],"blur",u.bind(this,function(){ia(this.R)}))};q.fa=function(){};q.k=function(){this.B("mouseout",u.bind(this,function(){ia(this.R);this.b.blur()}))};function ab(a,b){$.call(this,a,b)}t(ab,$);ab.prototype.p="captions";
ab.prototype.J="Captions";ab.prototype.className="vjs-captions-button";function bb(a,b){$.call(this,a,b)}t(bb,$);bb.prototype.p="subtitles";bb.prototype.J="Subtitles";bb.prototype.className="vjs-subtitles-button";function cb(a,b){$.call(this,a,b)}t(cb,$);q=cb.prototype;q.p="chapters";q.J="Chapters";q.className="vjs-chapters-button";q.Ra=function(){for(var a=[],b,d=0;d<X(this.a).length;d++)b=X(this.a)[d],b.z()===this.p&&a.push(new Z(this.a,{track:b}));return a};
q.ta=function(){for(var a=X(this.a),b=0,d=a.length,e,g,n=this.X=[];b<d;b++)if(e=a[b],e.z()==this.p&&e.ua()){if(2>e.readyState()){this.hc=e;e.d("loaded",u.bind(this,this.ta));return}g=e;break}a=this.R=new R(this.a);a.b.appendChild(u.c("li",{className:"vjs-menu-title",innerHTML:u.K(this.p)}));if(g){e=g.O;for(var l,b=0,d=e.length;b<d;b++)l=e[b],l=new db(this.a,{track:g,cue:l}),n.push(l),a.I(l)}this.I(a);0<this.X.length&&this.show();return a};
function db(a,b){var d=this.N=b.track,e=this.cue=b.cue,g=a.currentTime();b.label=e.text;b.selected=e.startTime<=g&&g<e.W;S.call(this,a,b);d.d("cuechange",u.bind(this,this.update))}t(db,S);db.prototype.k=function(){db.f.k.call(this);this.a.currentTime(this.cue.startTime);this.update(this.cue.startTime)};db.prototype.update=function(){var a=this.cue,b=this.a.currentTime();a.startTime<=b&&b<a.W?this.selected(f):this.selected(j)};u.g.t(D.prototype.e.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});if(JSON&&"function"===JSON.parse)u.JSON=JSON;else{u.JSON={};var fb=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;u.JSON.parse=function(a,b){function d(a,e){var l,s,p=a[e];if(p&&"object"===typeof p)for(l in p)Object.prototype.hasOwnProperty.call(p,l)&&(s=d(p,l),s!==c?p[l]=s:delete p[l]);return b.call(a,e,p)}var e;a=String(a);fb.lastIndex=0;fb.test(a)&&(a=a.replace(fb,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?d({"":e},""):e;throw new SyntaxError("JSON.parse");}};u.qa=function(){var a,b,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((b=d[e])&&b.getAttribute)b.player===c&&(a=b.getAttribute("data-setup"),a!==h&&(a=u.JSON.parse(a||"{}"),ba(b,a)));else{u.Oa();break}else u.bc||u.Oa()};u.Oa=function(){setTimeout(u.qa,1)};u.B(window,"load",function(){u.bc=f});u.qa();u.Pb=function(a,b){v.prototype[a]=b};r("videojs",u);r("_V_",u);r("videojs.options",u.options);r("videojs.cache",u.U);r("videojs.Component",x);x.prototype.dispose=x.prototype.w;x.prototype.createEl=x.prototype.c;x.prototype.getEl=x.prototype.Za;x.prototype.addChild=x.prototype.I;x.prototype.getChildren=x.prototype.lc;x.prototype.on=x.prototype.d;x.prototype.off=x.prototype.m;x.prototype.one=x.prototype.B;x.prototype.trigger=x.prototype.h;x.prototype.show=x.prototype.show;x.prototype.hide=x.prototype.s;x.prototype.width=x.prototype.width;
x.prototype.height=x.prototype.height;x.prototype.dimensions=x.prototype.Ab;r("videojs.Player",v);r("videojs.MediaLoader",xa);r("videojs.PosterImage",Ia);r("videojs.LoadingSpinner",J);r("videojs.BigPlayButton",I);r("videojs.ControlBar",D);r("videojs.TextTrackDisplay",Za);r("videojs.Control",C);r("videojs.ControlBar",D);r("videojs.Button",E);r("videojs.PlayButton",F);r("videojs.PauseButton",G);r("videojs.PlayToggle",ya);r("videojs.FullscreenToggle",H);r("videojs.BigPlayButton",I);
r("videojs.LoadingSpinner",J);r("videojs.CurrentTimeDisplay",K);r("videojs.DurationDisplay",L);r("videojs.TimeDivider",za);r("videojs.RemainingTimeDisplay",M);r("videojs.Slider",N);r("videojs.ProgressControl",O);r("videojs.SeekBar",P);r("videojs.LoadProgressBar",Ba);r("videojs.PlayProgressBar",Ca);r("videojs.SeekHandle",Da);r("videojs.VolumeControl",Ea);r("videojs.VolumeBar",Fa);r("videojs.VolumeLevel",Ga);r("videojs.VolumeHandle",Ha);r("videojs.MuteToggle",Q);r("videojs.PosterImage",Ia);
r("videojs.Menu",R);r("videojs.MenuItem",S);r("videojs.SubtitlesButton",bb);r("videojs.CaptionsButton",ab);r("videojs.ChaptersButton",cb);r("videojs.MediaTechController",T);r("videojs.Html5",U);U.Events=La;U.isSupported=function(){return!!document.createElement("video").canPlayType};U.canPlaySource=function(a){return!!document.createElement("video").canPlayType(a.type)};U.prototype.setCurrentTime=U.prototype.Tb;U.prototype.setVolume=U.prototype.Yb;U.prototype.setMuted=U.prototype.Wb;
U.prototype.setPreload=U.prototype.Xb;U.prototype.setAutoplay=U.prototype.Sb;U.prototype.setLoop=U.prototype.Vb;r("videojs.Flash",V);
V.isSupported=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(b){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return 10<=a.split(",")[0]};V.canPlaySource=function(a){if(a.type in V.prototype.C.Eb)return"maybe"};
V.onReady=V.onReady;r("videojs.TextTrack",Y);Y.prototype.label=Y.prototype.label;r("videojs.CaptionsTrack",Wa);r("videojs.SubtitlesTrack",Xa);r("videojs.ChaptersTrack",Ya);r("videojs.autoSetup",u.qa);r("videojs.plugin",u.Pb);
