var c=void 0,f=!0,h=null,j=!1;function k(a){return function(){return this[a]}}function m(a){return function(){return a}}var n,aa=this;aa.gc=f;Math.floor(2147483648*Math.random()).toString(36);function r(a,b){var d=a.split("."),e=aa;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&b!==c?e[g]=b:e=e[g]?e[g]:e[g]={}}function t(a,b){function d(){}d.prototype=b.prototype;a.e=b.prototype;a.prototype=new d;a.prototype.constructor=a};document.createElement("video");document.createElement("audio");function u(a,b,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(u.ma[a])return u.ma[a];a=u.j(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new v(a,b,d)}var ba=u;u.Qa="GENERATED_CDN_VSN";u.Pa="https:"==document.location.protocol?"https://":"http://";
u.options={techOrder:["html5","flash"],html5:{},flash:{vc:u.Pa+"vjs.zencdn.net/c/video-js.swf"},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}}};u.ma={};"GENERATED_CDN_VSN"!=u.Qa&&(ba.options.flash.swf=u.Pa+"vjs.zencdn.net/"+u.Qa+"/video-js.swf");u.nc={};u.d=function(a,b,d){var e=u.getData(a);e.p||(e.p={});e.p[b]||(e.p[b]=[]);d.n||(d.n=u.n++);e.p[b].push(d);e.I||(e.disabled=j,e.I=function(b){if(!e.disabled){b=u.Za(b);var d=e.p[b.type];if(d)for(var d=d.slice(0),l=0,s=d.length;l<s&&!b.eb();l++)d[l].call(a,b)}});1==e.p[b].length&&(document.addEventListener?a.addEventListener(b,e.I,j):document.attachEvent&&a.attachEvent("on"+b,e.I))};
u.m=function(a,b,d){if(u.cb(a)){var e=u.getData(a);if(e.p)if(b){var g=e.p[b];if(g){if(d){if(d.n)for(e=0;e<g.length;e++)g[e].n===d.n&&g.splice(e--,1)}else e.p[b]=[];u.Ta(a,b)}}else for(g in e.p)b=g,e.p[b]=[],u.Ta(a,b)}};u.Ta=function(a,b){var d=u.getData(a);0===d.p[b].length&&(delete d.p[b],document.removeEventListener?a.removeEventListener(b,d.I,j):document.detachEvent&&a.detachEvent("on"+b,d.I));u.Da(d.p)&&(delete d.p,delete d.I,delete d.disabled);u.Da(d)&&u.jb(a)};
u.Za=function(a){function b(){return f}function d(){return j}if(!a||!a.Ea){var e=a||window.event,g;for(g in e)a[g]=e[g];a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){a.returnValue=j;a.fa=b};a.fa=d;a.stopPropagation=function(){a.cancelBubble=f;a.Ea=b};a.Ea=d;a.stopImmediatePropagation=function(){a.eb=b;a.stopPropagation()};a.eb=d;a.clientX!=h&&(e=document.documentElement,g=document.body,a.pageX=a.clientX+(e&&
e.scrollLeft||g&&g.scrollLeft||0)-(e&&e.clientLeft||g&&g.clientLeft||0),a.pageY=a.clientY+(e&&e.scrollTop||g&&g.scrollTop||0)-(e&&e.clientTop||g&&g.clientTop||0));a.which=a.charCode||a.keyCode;a.button!=h&&(a.button=a.button&1?0:a.button&4?1:a.button&2?2:0)}return a};
u.h=function(a,b){var d=u.cb(a)?u.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof b&&(b={type:b,target:a});b=u.Za(b);d.I&&d.I.call(a,b);if(e&&!b.Ea())u.h(e,b);else if(!e&&!b.fa()&&(d=u.getData(b.target),b.target[b.type])){d.disabled=f;if("function"===typeof b.target[b.type])b.target[b.type]();d.disabled=j}return!b.fa()};u.F=function(a,b,d){u.d(a,b,function(){u.m(a,b,arguments.callee);d.apply(this,arguments)})};u.mc={};u.c=function(a,b){var d=document.createElement(a||"div"),e;for(e in b)b.hasOwnProperty(e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,b[e]):d[e]=b[e]);return d};u.L=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};u.g={};u.g.toString=Object.prototype.toString;u.g.hasOwnProperty=Object.prototype.hasOwnProperty;u.g.W=function(a,b,d){for(var e in a)u.g.hasOwnProperty.call(a,e)&&b.call(d||this,e,a[e])};
u.g.t=function(a,b){if(!b)return a;for(var d in b)u.g.hasOwnProperty.call(b,d)&&(a[d]=b[d]);return a};u.g.Ya=function(a,b){var d,e,g;a=u.g.copy(a);for(d in b)u.g.hasOwnProperty.call(b,d)&&(e=a[d],g=b[d],a[d]="[object Object]"===u.g.toString.call(e)&&"[object Object]"===u.g.toString.call(g)?u.g.Ya(e,g):b[d]);return a};u.g.copy=function(a){return u.g.t({},a)};u.bind=function(a,b,d){function e(){return b.apply(a,arguments)}b.n||(b.n=u.n++);e.n=d?d+"_"+b.n:b.n;return e};u.V={};u.n=1;
u.expando="vdata"+(new Date).getTime();u.getData=function(a){var b=a[u.expando];b||(b=a[u.expando]=u.n++,u.V[b]={});return u.V[b]};u.cb=function(a){a=a[u.expando];return!(!a||u.Da(u.V[a]))};u.jb=function(a){var b=a[u.expando];if(b){delete u.V[b];try{delete a[u.expando]}catch(d){a.removeAttribute?a.removeAttribute(u.expando):a[u.expando]=h}}};u.Da=function(a){for(var b in a)if(a[b]!==h)return j;return f};
u.o=function(a,b){-1==(" "+a.className+" ").indexOf(" "+b+" ")&&(a.className=""===a.className?b:a.className+" "+b)};u.u=function(a,b){if(-1!=a.className.indexOf(b)){var d=a.className.split(" ");d.splice(d.indexOf(b),1);a.className=d.join(" ")}};u.wb=u.c("video");u.A=navigator.userAgent;u.ub=!!u.A.match(/iPad/i);u.tb=!!u.A.match(/iPhone/i);u.vb=!!u.A.match(/iPod/i);u.sb=u.ub||u.tb||u.vb;var ca=u,da;var ea=u.A.match(/OS (\d+)_/i);da=ea&&ea[1]?ea[1]:c;ca.hc=da;u.qb=!!u.A.match(/Android.*AppleWebKit/i);
var fa=u,ga=u.A.match(/Android (\d+)\./i);fa.pb=ga&&ga[1]?ga[1]:h;u.rb=function(){return!!u.A.match("Firefox")};u.Aa=function(a){var b={};if(a&&a.attributes&&0<a.attributes.length)for(var d=a.attributes,e,g,p=d.length-1;0<=p;p--){e=d[p].name;g=d[p].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==h?f:j;b[e]=g}return b};
u.pc=function(a,b){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(b):a.currentStyle&&(b=b.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),d=a.currentStyle[b]);return d};u.Ca=function(a,b){b.firstChild?b.insertBefore(a,b.firstChild):b.appendChild(a)};u.Oa={};u.j=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
u.ea=function(a,b){b=b||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),p=Math.floor(b/60%60),l=Math.floor(b/3600),g=0<g||0<l?g+":":"";return g+(((g||10<=p)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};u.zb=function(){document.body.focus();document.onselectstart=m(j)};u.cc=function(){document.onselectstart=m(f)};u.trim=function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")};u.round=function(a,b){b||(b=0);return Math.round(a*Math.pow(10,b))/Math.pow(10,b)};
u.Wa=function(a){return{length:1,start:m(0),end:function(){return a}}};
u.get=function(a,b,d){var e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});var g=new XMLHttpRequest;try{g.open("GET",a)}catch(p){d(p)}g.onreadystatechange=
function(){4===g.readyState&&(200===g.status||e&&0===g.status?b(g.responseText):d&&d())};try{g.send()}catch(l){d&&d(l)}};u.Xb=function(a){var b=window.localStorage||j;if(b)try{b.volume=a}catch(d){22==d.code||1014==d.code?u.log("LocalStorage Full (VideoJS)",d):u.log("LocalStorage Error (VideoJS)",d)}};u.bb=function(a){a.match(/^https?:\/\//)||(a=u.c("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
u.log=function(){u.log.history=u.log.history||[];u.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};u.Fb="getBoundingClientRect"in document.documentElement?function(a){var b;try{b=a.getBoundingClientRect()}catch(d){}if(!b)return 0;a=document.body;return b.left+(window.pageXOffset||a.scrollLeft)-(document.documentElement.clientLeft||a.clientLeft||0)}:function(a){for(var b=a.offsetLeft;a=a.offsetParent;)b+=a.offsetLeft;return b};function x(a,b,d){this.b=a;this.f=u.g.copy(this.f);b=this.options(b);this.B=b.id||(b.el&&b.el.id?b.el.id:a.id()+"_component_"+u.n++);this.Kb=b.name||h;this.a=b.el||this.c();this.v=[];this.va={};this.H={};if((a=this.f)&&a.children){var e=this;u.g.W(a.children,function(a,b){b!==j&&!b.loadEvent&&(e[a]=e.J(a,b))})}y(this,d)}n=x.prototype;
n.w=function(){if(this.v)for(var a=this.v.length-1;0<=a;a--)this.v[a].w&&this.v[a].w();this.H=this.va=this.v=h;this.m();this.a.parentNode&&this.a.parentNode.removeChild(this.a);u.jb(this.a);this.a=h};n.Rb=k("b");n.options=function(a){return a===c?this.f:this.f=u.g.Ya(this.f,a)};n.c=function(a,b){return u.c(a,b)};n.j=k("a");n.id=k("B");n.name=k("Kb");n.children=k("v");
n.J=function(a,b){var d,e;"string"===typeof a?(e=a,b=b||{},d=b.componentClass||u.L(e),b.name=e,d=new window.videojs[d](this.b||this,b)):d=a;this.v.push(d);"function"===typeof d.id&&(this.va[d.id()]=d);(e=e||d.name&&d.name())&&(this.H[e]=d);"function"===typeof d.j&&d.j()&&this.a.appendChild(d.j());return d};
n.removeChild=function(a){"string"===typeof a&&(a=this.H[a]);if(a&&this.v){for(var b=j,d=this.v.length-1;0<=d;d--)if(this.v[d]===a){b=f;this.v.splice(d,1);break}b&&(this.va[a.id]=h,this.H[a.name]=h,(b=a.j())&&b.parentNode===this.a&&this.a.removeChild(a.j()))}};n.r=m("");n.d=function(a,b){u.d(this.a,a,u.bind(this,b));return this};n.m=function(a,b){u.m(this.a,a,b);return this};n.F=function(a,b){u.F(this.a,a,u.bind(this,b));return this};n.h=function(a,b){u.h(this.a,a,b);return this};
function y(a,b){b&&(a.R?b.call(a):(a.pa===c&&(a.pa=[]),a.pa.push(b)))}function ha(a){a.R=f;var b=a.pa;if(b&&0<b.length){for(var d=0,e=b.length;d<e;d++)b[d].call(a);a.pa=[];a.h("ready")}}n.o=function(a){u.o(this.a,a);return this};n.u=function(a){u.u(this.a,a);return this};n.show=function(){this.a.style.display="block";return this};n.s=function(){this.a.style.display="none";return this};n.da=function(){this.u("vjs-fade-out");this.o("vjs-fade-in");return this};
n.ya=function(){this.u("vjs-fade-in");this.o("vjs-fade-out");return this};n.fb=function(){var a=this.a.style;a.display="block";a.opacity=1;a.ec="visible";return this};function ia(a){a=a.a.style;a.display="";a.opacity="";a.ec=""}n.width=function(a,b){return ja(this,"width",a,b)};n.height=function(a,b){return ja(this,"height",a,b)};n.Cb=function(a,b){return this.width(a,f).height(b)};
function ja(a,b,d,e){if(d!==c)return a.a.style[b]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:d+"px",e||a.h("resize"),a;if(!a.a)return 0;d=a.a.style[b];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.a["offset"+u.L(b)],10)};function v(a,b,d){this.G=a;b=u.g.t(ka(a),b);this.l={};this.hb=b.poster;this.Ua=b.controls;x.call(this,this,b,d);this.F("play",function(a){u.h(this.a,{type:"firstplay",target:this.a})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())});this.d("ended",this.Mb);this.d("play",this.La);this.d("firstplay",this.Nb);this.d("pause",this.Ka);this.d("progress",this.Pb);this.d("durationchange",this.Lb);this.d("error",this.Ia);this.d("fullscreenchange",this.Ob);u.ma[this.B]=this;b.plugins&&
u.g.W(b.plugins,function(a,b){this[a](b)},this)}t(v,x);n=v.prototype;n.f=u.options;n.w=function(){u.ma[this.B]=h;this.G&&this.G.player&&(this.G.player=h);this.a&&this.a.player&&(this.a.player=h);clearInterval(this.oa);this.Z();this.i&&this.i.w();v.e.w.call(this)};
function ka(a){var b={sources:[],tracks:[]};u.g.t(b,u.Aa(a));if(a.hasChildNodes())for(var d,e=a.childNodes,g=0,p=e.length;g<p;g++)a=e[g],d=a.nodeName.toLowerCase(),"source"===d?b.sources.push(u.Aa(a)):"track"===d&&b.tracks.push(u.Aa(a));return b}
n.c=function(){var a=this.a=v.e.c.call(this,"div"),b=this.G;b.removeAttribute("controls");b.removeAttribute("poster");b.removeAttribute("width");b.removeAttribute("height");if(b.hasChildNodes())for(var d=b.childNodes.length,e=0,g=b.childNodes;e<d;e++)("source"==g[0].nodeName.toLowerCase()||"track"==g[0].nodeName.toLowerCase())&&b.removeChild(g[0]);b.id=b.id||"vjs_video_"+u.n++;a.id=b.id;a.className=b.className;b.id+="_html5_api";b.className="vjs-tech";b.player=a.player=this;this.o("vjs-paused");this.width(this.f.width,
f);this.height(this.f.height,f);b.parentNode&&b.parentNode.insertBefore(a,b);u.Ca(b,a);return a};
function la(a,b,d){a.i?ma(a):"Html5"!==b&&a.G&&(a.a.removeChild(a.G),a.G=h);a.N=b;a.R=j;var e=u.g.t({source:d,tc:a.a},a.f[b.toLowerCase()]);d&&(d.src==a.l.src&&0<a.l.currentTime&&(e.startTime=a.l.currentTime),a.l.src=d.src);a.i=new window.videojs[b](a,e);y(a.i,function(){ha(this.b);if(!this.C.ib){var a=this.b;a.Ga=f;a.oa=setInterval(u.bind(a,function(){this.l.ua<this.buffered().end(0)?this.h("progress"):1==na(this)&&(clearInterval(this.oa),this.h("progress"))}),500);a.i.F("progress",function(){this.C.ib=
f;var a=this.b;a.Ga=j;clearInterval(a.oa)})}this.C.nb||(a=this.b,a.Ha=f,a.d("play",a.ob),a.d("pause",a.Z),a.i.F("timeupdate",function(){this.C.nb=f;oa(this.b)}))})}function ma(a){a.i.w();a.Ga&&(a.Ga=j,clearInterval(a.oa));a.Ha&&oa(a);a.i=j}function oa(a){a.Ha=j;a.Z();a.m("play",a.ob);a.m("pause",a.Z)}n.ob=function(){this.Xa&&this.Z();this.Xa=setInterval(u.bind(this,function(){this.h("timeupdate")}),250)};n.Z=function(){clearInterval(this.Xa)};n.Mb=function(){this.f.loop&&(this.currentTime(0),this.play())};
n.La=function(){u.u(this.a,"vjs-paused");u.o(this.a,"vjs-playing")};n.Nb=function(){this.f.starttime&&this.currentTime(this.f.starttime)};n.Ka=function(){u.u(this.a,"vjs-playing");u.o(this.a,"vjs-paused")};n.Pb=function(){1==na(this)&&this.h("loadedalldata")};n.Lb=function(){this.duration(z(this,"duration"))};n.Ia=function(a){u.log("Video Error",a)};n.Ob=function(){this.D?this.o("vjs-fullscreen"):this.u("vjs-fullscreen")};
function A(a,b,d){if(a.i&&a.i.R)y(a.i,function(){this[b](d)});else try{a.i[b](d)}catch(e){u.log(e)}}function z(a,b){if(a.i.R)try{return a.i[b]()}catch(d){if(a.i[b]===c)u.log("Video.js: "+b+" method not defined for "+a.N+" playback technology.",d);else{if("TypeError"==d.name)throw u.log("Video.js: "+b+" unavailable on "+a.N+" playback technology element.",d),a.i.R=j,d;u.log(d)}}}n.play=function(){var a={type:"play",target:this.a};this.h(a);a.fa()||A(this,"play");return this};
n.pause=function(){A(this,"pause");return this};n.paused=function(){return z(this,"paused")===j?j:f};n.currentTime=function(a){return a!==c?(this.l.rc=a,A(this,"setCurrentTime",a),this.Ha&&this.h("timeupdate"),this):this.l.currentTime=z(this,"currentTime")||0};n.duration=function(a){return a!==c?(this.l.duration=parseFloat(a),this):this.l.duration};n.buffered=function(){var a=z(this,"buffered"),b=this.l.ua=this.l.ua||0;a&&(0<a.length&&a.end(0)!==b)&&(b=a.end(0),this.l.ua=b);return u.Wa(b)};
function na(a){return a.duration()?a.buffered().end(0)/a.duration():0}n.volume=function(a){if(a!==c)return a=Math.max(0,Math.min(1,parseFloat(a))),this.l.volume=a,A(this,"setVolume",a),u.Xb(a),this;a=parseFloat(z(this,"volume"));return isNaN(a)?1:a};n.muted=function(a){return a!==c?(A(this,"setMuted",a),this):z(this,"muted")||j};n.ra=function(){return z(this,"supportsFullScreen")||j};
n.qa=function(){var a=u.Oa.qa;this.D=f;a?(u.d(document,a.Q,u.bind(this,function(){this.D=document[a.D];this.D===j&&u.m(document,a.Q,arguments.callee);this.h("fullscreenchange")})),this.i.C.ab===j&&this.f.flash.iFrameMode!==f&&(this.pause(),ma(this),u.d(document,a.Q,u.bind(this,function(){u.m(document,a.Q,arguments.callee);la(this,this.N,{src:this.l.src})}))),this.a[a.Tb]()):this.i.ra()?(this.h("fullscreenchange"),A(this,"enterFullScreen")):(this.h("fullscreenchange"),this.Hb=f,this.Db=document.documentElement.style.overflow,
u.d(document,"keydown",u.bind(this,this.$a)),document.documentElement.style.overflow="hidden",u.o(document.body,"vjs-full-window"),u.o(this.a,"vjs-fullscreen"),this.h("enterFullWindow"));return this};function pa(a){var b=u.Oa.qa;a.D=j;b?(a.i.C.ab===j&&a.f.flash.iFrameMode!==f&&(a.pause(),ma(a),u.d(document,b.Q,u.bind(a,function(){u.m(document,b.Q,arguments.callee);la(this,this.N,{src:this.l.src})}))),document[b.Ab]()):(a.i.ra()?A(a,"exitFullScreen"):qa(a),a.h("fullscreenchange"))}
n.$a=function(a){27===a.keyCode&&(this.D===f?pa(this):qa(this))};function qa(a){a.Hb=j;u.m(document,"keydown",a.$a);document.documentElement.style.overflow=a.Db;u.u(document.body,"vjs-full-window");u.u(a.a,"vjs-fullscreen");a.h("exitFullWindow")}
n.src=function(a){if(a instanceof Array){var b;a:{b=a;for(var d=0,e=this.f.techOrder;d<e.length;d++){var g=u.L(e[d]),p=window.videojs[g];if(p.isSupported())for(var l=0,s=b;l<s.length;l++){var q=s[l];if(p.canPlaySource(q)){b={source:q,i:g};break a}}}b=j}b?(a=b.source,b=b.i,b==this.N?this.src(a):la(this,b,a)):this.a.appendChild(u.c("p",{innerHTML:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://www.google.com/chrome">Google Chrome</a> or download the latest <a href="http://get.adobe.com/flashplayer/">Adobe Flash Player</a>.'}))}else a instanceof
Object?window.videojs[this.N].canPlaySource(a)?this.src(a.src):this.src([a]):(this.l.src=a,this.R?(A(this,"src",a),"auto"==this.f.preload&&this.load(),this.f.autoplay&&this.play()):y(this,function(){this.src(a)}));return this};n.load=function(){A(this,"load");return this};n.currentSrc=function(){return z(this,"currentSrc")||this.l.src||""};n.na=function(a){return a!==c?(A(this,"setPreload",a),this.f.preload=a,this):z(this,"preload")};
n.autoplay=function(a){return a!==c?(A(this,"setAutoplay",a),this.f.autoplay=a,this):z(this,"autoplay")};n.loop=function(a){return a!==c?(A(this,"setLoop",a),this.f.loop=a,this):z(this,"loop")};n.poster=function(a){a!==c&&(this.hb=a);return this.hb};n.controls=function(a){a!==c&&(this.Ua=a);return this.Ua};n.error=function(){return z(this,"error")};var ra,sa,ta,ua;
if(document.kc!==c)ra="requestFullscreen",sa="exitFullscreen",ta="fullscreenchange",ua="fullScreen";else for(var va=["moz","webkit"],wa=va.length-1;0<=wa;wa--){var B=va[wa];if(("moz"!=B||document.mozFullScreenEnabled)&&document[B+"CancelFullScreen"]!==c)ra=B+"RequestFullScreen",sa=B+"CancelFullScreen",ta=B+"fullscreenchange",ua="webkit"==B?B+"IsFullScreen":B+"FullScreen"}ra&&(u.Oa.qa={Tb:ra,Ab:sa,Q:ta,D:ua});
function xa(a,b,d){x.call(this,a,b,d);if(!a.f.sources||0===a.f.sources.length){b=0;for(d=a.f.techOrder;b<d.length;b++){var e=u.L(d[b]),g=window.videojs[e];if(g&&g.isSupported()){la(a,e);break}}}else a.src(a.f.sources)}t(xa,x);function C(a,b){x.call(this,a,b)}t(C,x);C.prototype.r=function(){return"vjs-control "+C.e.r.call(this)};function D(a,b){x.call(this,a,b);a.F("play",u.bind(this,function(){this.da();this.b.d("mouseover",u.bind(this,this.da));this.b.d("mouseout",u.bind(this,this.ya))}))}t(D,x);n=D.prototype;n.f={sc:"play",children:{playToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},progressControl:{},fullscreenToggle:{},volumeControl:{},muteToggle:{}}};
n.c=function(){return u.c("div",{className:"vjs-control-bar"})};n.da=function(){D.e.da.call(this);this.b.h("controlsvisible")};n.ya=function(){D.e.ya.call(this);this.b.h("controlshidden")};n.fb=function(){this.a.style.opacity="1"};function E(a,b){x.call(this,a,b);this.d("click",this.k);this.d("focus",this.ja);this.d("blur",this.ia)}t(E,C);n=E.prototype;
n.c=function(a,b){b=u.g.t({className:this.r(),innerHTML:'<div><span class="vjs-control-text">'+(this.K||"Need Text")+"</span></div>",Ub:"button","aria-live":"polite",tabIndex:0},b);return E.e.c.call(this,a,b)};n.k=function(){};n.ja=function(){u.d(document,"keyup",u.bind(this,this.M))};n.M=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.k()};n.ia=function(){u.m(document,"keyup",u.bind(this,this.M))};function F(a,b){E.call(this,a,b)}t(F,E);F.prototype.K="Play";
F.prototype.r=function(){return"vjs-play-button "+F.e.r.call(this)};F.prototype.k=function(){this.b.play()};function G(a,b){E.call(this,a,b)}t(G,E);G.prototype.K="Play";G.prototype.r=function(){return"vjs-pause-button "+G.e.r.call(this)};G.prototype.k=function(){this.b.pause()};function ya(a,b){E.call(this,a,b);a.d("play",u.bind(this,this.La));a.d("pause",u.bind(this,this.Ka))}t(ya,E);n=ya.prototype;n.K="Play";n.r=function(){return"vjs-play-control "+ya.e.r.call(this)};
n.k=function(){this.b.paused()?this.b.play():this.b.pause()};n.La=function(){u.u(this.a,"vjs-paused");u.o(this.a,"vjs-playing");this.a.children[0].children[0].innerHTML="Pause"};n.Ka=function(){u.u(this.a,"vjs-playing");u.o(this.a,"vjs-paused");this.a.children[0].children[0].innerHTML="Play"};function H(a,b){E.call(this,a,b)}t(H,E);H.prototype.K="Fullscreen";H.prototype.r=function(){return"vjs-fullscreen-control "+H.e.r.call(this)};
H.prototype.k=function(){this.b.D?(pa(this.b),this.a.children[0].children[0].innerHTML="Fullscreen"):(this.b.qa(),this.a.children[0].children[0].innerHTML="Non-Fullscreen")};function I(a,b){E.call(this,a,b);a.d("play",u.bind(this,this.s))}t(I,E);I.prototype.c=function(){return I.e.c.call(this,"div",{className:"vjs-big-play-button",innerHTML:"<span></span>","aria-label":"play video"})};I.prototype.k=function(){this.b.currentTime()&&this.b.currentTime(0);this.b.play()};
function J(a,b){x.call(this,a,b);a.d("canplay",u.bind(this,this.s));a.d("canplaythrough",u.bind(this,this.s));a.d("playing",u.bind(this,this.s));a.d("seeked",u.bind(this,this.s));a.d("seeking",u.bind(this,this.show));a.d("seeked",u.bind(this,this.s));a.d("error",u.bind(this,this.show));a.d("waiting",u.bind(this,this.show))}t(J,x);
J.prototype.c=function(){var a,b;"string"==typeof this.b.j().style.WebkitBorderRadius||"string"==typeof this.b.j().style.MozBorderRadius||"string"==typeof this.b.j().style.ic||"string"==typeof this.b.j().style.jc?(a="vjs-loading-spinner",b='<div class="ball1"></div><div class="ball2"></div><div class="ball3"></div><div class="ball4"></div><div class="ball5"></div><div class="ball6"></div><div class="ball7"></div><div class="ball8"></div>'):(a="vjs-loading-spinner-fallback",b="");return J.e.c.call(this,
"div",{className:a,innerHTML:b})};function K(a,b){x.call(this,a,b);a.d("timeupdate",u.bind(this,this.ba))}t(K,x);K.prototype.c=function(){var a=K.e.c.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.content=u.c("div",{className:"vjs-current-time-display",innerHTML:'<span class="vjs-control-text">Current Time </span>0:00',"aria-live":"off"});a.appendChild(u.c("div").appendChild(this.content));return a};
K.prototype.ba=function(){var a=this.b.Na?this.b.l.currentTime:this.b.currentTime();this.content.innerHTML='<span class="vjs-control-text">Current Time </span>'+u.ea(a,this.b.duration())};function L(a,b){x.call(this,a,b);a.d("timeupdate",u.bind(this,this.ba))}t(L,x);
L.prototype.c=function(){var a=L.e.c.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.content=u.c("div",{className:"vjs-duration-display",innerHTML:'<span class="vjs-control-text">Duration Time </span>-0:00',"aria-live":"off"});a.appendChild(u.c("div").appendChild(this.content));return a};L.prototype.ba=function(){this.b.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Duration Time </span>-'+u.ea(this.b.duration()))};
function za(a,b){x.call(this,a,b)}t(za,x);za.prototype.c=function(){return za.e.c.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};function M(a,b){x.call(this,a,b);a.d("timeupdate",u.bind(this,this.ba))}t(M,x);
M.prototype.c=function(){var a=M.e.c.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.content=u.c("div",{className:"vjs-remaining-time-display",innerHTML:'<span class="vjs-control-text">Remaining Time </span>-0:00',"aria-live":"off"});a.appendChild(u.c("div").appendChild(this.content));return a};
M.prototype.ba=function(){this.b.duration()&&this.b.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Remaining Time </span>-'+u.ea(this.b.duration()-this.b.currentTime()))};function N(a,b){x.call(this,a,b);this.yb=this.H[this.f.barName];this.handle=this.H[this.f.handleName];a.d(this.gb,u.bind(this,this.update));this.d("mousedown",this.Ja);this.d("focus",this.ja);this.d("blur",this.ia);this.b.d("controlsvisible",u.bind(this,this.update));y(a,u.bind(this,this.update))}t(N,x);n=N.prototype;
n.c=function(a,b){b=u.g.t({Ub:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},b);return N.e.c.call(this,a,b)};n.Ja=function(a){a.preventDefault();u.zb();u.d(document,"mousemove",u.bind(this,this.ka));u.d(document,"mouseup",u.bind(this,this.la));this.ka(a)};n.la=function(){u.cc();u.m(document,"mousemove",this.ka,j);u.m(document,"mouseup",this.la,j);this.update()};
n.update=function(){var a,b=this.Ba(),d=this.handle,e=this.yb;isNaN(b)&&(b=0);a=b;if(d){a=this.a.offsetWidth;var g=d.j().offsetWidth;a=g?g/a:0;b*=1-a;a=b+a/2;d.j().style.left=u.round(100*b,2)+"%"}e.j().style.width=u.round(100*a,2)+"%"};function Aa(a,b){var d=a.a,e=u.Fb(d),d=d.offsetWidth,g=a.handle;g&&(g=g.j().offsetWidth,e+=g/2,d-=g);return Math.max(0,Math.min(1,(b.pageX-e)/d))}n.ja=function(){u.d(document,"keyup",u.bind(this,this.M))};
n.M=function(a){37==a.which?(a.preventDefault(),this.lb()):39==a.which&&(a.preventDefault(),this.mb())};n.ia=function(){u.m(document,"keyup",u.bind(this,this.M))};function O(a,b){x.call(this,a,b)}t(O,x);O.prototype.f={children:{seekBar:{}}};O.prototype.c=function(){return O.e.c.call(this,"div",{className:"vjs-progress-control vjs-control"})};function P(a,b){N.call(this,a,b);a.d("timeupdate",u.bind(this,this.aa));y(a,u.bind(this,this.aa))}t(P,N);n=P.prototype;
n.f={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};n.gb="timeupdate";n.c=function(){return P.e.c.call(this,"div",{className:"vjs-progress-holder","aria-label":"video progress bar"})};n.aa=function(){var a=this.b.Na?this.b.l.currentTime:this.b.currentTime();this.a.setAttribute("aria-valuenow",u.round(100*this.Ba(),2));this.a.setAttribute("aria-valuetext",u.ea(a,this.b.duration()))};n.Ba=function(){return this.b.currentTime()/this.b.duration()};
n.Ja=function(a){P.e.Ja.call(this,a);this.b.Na=f;this.dc=!this.b.paused();this.b.pause()};n.ka=function(a){a=Aa(this,a)*this.b.duration();a==this.b.duration()&&(a-=0.1);this.b.currentTime(a)};n.la=function(a){P.e.la.call(this,a);this.b.Na=j;this.dc&&this.b.play()};n.mb=function(){this.b.currentTime(this.b.currentTime()+5)};n.lb=function(){this.b.currentTime(this.b.currentTime()-5)};function Ba(a,b){x.call(this,a,b);a.d("progress",u.bind(this,this.update))}t(Ba,x);
Ba.prototype.c=function(){return Ba.e.c.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};Ba.prototype.update=function(){this.a.style&&(this.a.style.width=u.round(100*na(this.b),2)+"%")};function Ca(a,b){x.call(this,a,b)}t(Ca,x);Ca.prototype.c=function(){return Ca.e.c.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};function Da(a,b){x.call(this,a,b)}t(Da,x);
Da.prototype.c=function(){return Da.e.c.call(this,"div",{className:"vjs-seek-handle",innerHTML:'<span class="vjs-control-text">00:00</span>'})};function Ea(a,b){x.call(this,a,b)}t(Ea,x);Ea.prototype.f={children:{volumeBar:{}}};Ea.prototype.c=function(){return Ea.e.c.call(this,"div",{className:"vjs-volume-control vjs-control"})};function Fa(a,b){N.call(this,a,b);a.d("volumechange",u.bind(this,this.aa));y(a,u.bind(this,this.aa));setTimeout(u.bind(this,this.update),0)}t(Fa,N);n=Fa.prototype;
n.aa=function(){this.a.setAttribute("aria-valuenow",u.round(100*this.b.volume(),2));this.a.setAttribute("aria-valuetext",u.round(100*this.b.volume(),2)+"%")};n.f={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};n.gb="volumechange";n.c=function(){return Fa.e.c.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};n.ka=function(a){this.b.volume(Aa(this,a))};n.Ba=function(){return this.b.volume()};
n.mb=function(){this.b.volume(this.b.volume()+0.1)};n.lb=function(){this.b.volume(this.b.volume()-0.1)};function Ga(a,b){x.call(this,a,b)}t(Ga,x);Ga.prototype.c=function(){return Ga.e.c.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};function Ha(a,b){x.call(this,a,b)}t(Ha,x);Ha.prototype.c=function(){return Ha.e.c.call(this,"div",{className:"vjs-volume-handle",innerHTML:'<span class="vjs-control-text"></span>'})};
function Q(a,b){E.call(this,a,b);a.d("volumechange",u.bind(this,this.update))}t(Q,E);Q.prototype.c=function(){return Q.e.c.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};Q.prototype.k=function(){this.b.muted(this.b.muted()?j:f)};
Q.prototype.update=function(){var a=this.b.volume(),b=3;0===a||this.b.muted()?b=0:0.33>a?b=1:0.67>a&&(b=2);this.b.muted()?"Unmute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Unmute"):"Mute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Mute");for(a=0;4>a;a++)u.u(this.a,"vjs-vol-"+a);u.o(this.a,"vjs-vol-"+b)};function Ia(a,b){E.call(this,a,b);a.poster()||this.s();a.d("play",u.bind(this,this.s))}t(Ia,E);
Ia.prototype.c=function(){var a=u.c("img",{className:"vjs-poster",tabIndex:-1});this.b.poster()&&(a.src=this.b.poster());return a};Ia.prototype.k=function(){this.b.play()};function R(a,b){x.call(this,a,b)}t(R,x);function Ja(a,b){a.J(b);b.d("click",u.bind(a,function(){ia(this)}))}R.prototype.c=function(){return R.e.c.call(this,"ul",{className:"vjs-menu"})};
function S(a,b){E.call(this,a,b);b.selected?(this.o("vjs-selected"),this.a.setAttribute("aria-selected",f)):this.a.setAttribute("aria-selected",j)}t(S,E);S.prototype.c=function(a,b){return S.e.c.call(this,"li",u.g.t({className:"vjs-menu-item",innerHTML:this.f.label},b))};S.prototype.k=function(){this.selected(f)};S.prototype.selected=function(a){a?(this.o("vjs-selected"),this.a.setAttribute("aria-selected",f)):(this.u("vjs-selected"),this.a.setAttribute("aria-selected",j))};function T(a,b,d){x.call(this,a,b,d)}t(T,x);T.prototype.k=function(){this.b.controls()&&(this.b.paused()?this.b.play():this.b.pause())};u.media={};u.media.sa="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function Ka(){var a=u.media.sa[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=u.media.sa.length-1;0<=i;i--)T.prototype[u.media.sa[i]]=Ka();function U(a,b,d){x.call(this,a,b,d);(b=b.source)&&this.a.currentSrc==b.src?a.h("loadstart"):b&&(this.a.src=b.src);y(a,function(){this.f.autoplay&&this.paused()&&(this.G.poster=h,this.play())});this.d("click",this.k);for(a=La.length-1;0<=a;a--)u.d(this.a,La[a],u.bind(this.b,this.Eb));ha(this)}t(U,T);n=U.prototype;n.w=function(){U.e.w.call(this)};
n.c=function(){var a=this.b,b=a.G;if(!b||this.C.Jb===j)b?(a.j().removeChild(b),b=b.cloneNode(j)):b=u.c("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),u.Ca(b,a.j());for(var d=["autoplay","preload","loop","muted"],e=d.length-1;0<=e;e--){var g=d[e];a.f[g]!==h&&(b[g]=a.f[g])}return b};n.Eb=function(a){"play"!==a.type&&(this.h(a),a.stopPropagation())};n.play=function(){this.a.play()};n.pause=function(){this.a.pause()};n.paused=function(){return this.a.paused};n.currentTime=function(){return this.a.currentTime};
n.Wb=function(a){try{this.a.currentTime=a}catch(b){u.log(b,"Video is not ready. (Video.js)")}};n.duration=function(){return this.a.duration||0};n.buffered=function(){return this.a.buffered};n.volume=function(){return this.a.volume};n.ac=function(a){this.a.volume=a};n.muted=function(){return this.a.muted};n.Zb=function(a){this.a.muted=a};n.width=function(){return this.a.offsetWidth};n.height=function(){return this.a.offsetHeight};
n.ra=function(){return"function"==typeof this.a.webkitEnterFullScreen&&!navigator.userAgent.match("Chrome")&&!navigator.userAgent.match("Mac OS X 10.5")?f:j};n.src=function(a){this.a.src=a};n.load=function(){this.a.load()};n.currentSrc=function(){return this.a.currentSrc};n.na=function(){return this.a.na};n.$b=function(a){this.a.na=a};n.autoplay=function(){return this.a.autoplay};n.Vb=function(a){this.a.autoplay=a};n.loop=function(){return this.a.loop};n.Yb=function(a){this.a.loop=a};n.error=function(){return this.a.error};
var La="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");U.prototype.C={oc:u.wb.webkitEnterFullScreen?!u.A.match("Chrome")&&!u.A.match("Mac OS X 10.5")?f:j:j,Jb:!u.sb};u.qb&&3>u.pb&&(document.createElement("video").constructor.prototype.canPlayType=function(a){return a&&-1!=a.toLowerCase().indexOf("video/mp4")?"maybe":""});function V(a,b,d){x.call(this,a,b,d);var e=b.source,g=b.parentEl;d=this.a=u.c("div",{id:a.id()+"_temp_flash"});var p=a.id()+"_flash_api";a=a.f;var l=u.g.t({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.na,loop:a.loop,muted:a.muted},b.flashVars),s=u.g.t({wmode:"opaque",bgcolor:"#000000"},b.params),q=u.g.t({id:p,name:p,"class":"vjs-tech"},b.attributes);e&&(l.src=encodeURIComponent(u.bb(e.src)));
u.Ca(d,g);b.startTime&&y(this,function(){this.load();this.play();this.currentTime(b.startTime)});if(b.iFrameMode===f&&!u.rb){var w=u.c("iframe",{id:p+"_iframe",name:p+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});l.readyFunction="ready";l.eventProxyFunction="events";l.errorEventProxyFunction="errors";u.d(w,"load",u.bind(this,function(){var a,d=w.contentWindow;a=w.contentDocument?w.contentDocument:w.contentWindow.document;a.write(Ma(b.swf,l,s,q));d.player=
this.b;d.ready=u.bind(this.b,function(b){b=a.getElementById(b);var d=this.i;d.a=b;u.d(b,"click",d.bind(d.k));Na(d)});d.events=u.bind(this.b,function(a,b){this&&"flash"===this.N&&this.h(b)});d.errors=u.bind(this.b,function(a,b){u.log("Flash Error",b)})}));d.parentNode.replaceChild(w,d)}else{a=Ma(b.swf,l,s,q);a=u.c("div",{innerHTML:a}).childNodes[0];e=d.parentNode;d.parentNode.replaceChild(a,d);var gb=e.childNodes[0];setTimeout(function(){gb.style.display="block"},1E3)}}t(V,T);n=V.prototype;n.w=function(){V.e.w.call(this)};
n.play=function(){this.a.vjs_play()};n.pause=function(){this.a.vjs_pause()};n.src=function(a){a=u.bb(a);this.a.vjs_src(a);if(this.b.autoplay()){var b=this;setTimeout(function(){b.play()},0)}};n.load=function(){this.a.vjs_load()};n.poster=function(){this.a.vjs_getProperty("poster")};n.buffered=function(){return u.Wa(this.a.vjs_getProperty("buffered"))};n.ra=m(j);
var Oa=V.prototype,Pa="preload currentTime defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),Qa="error currentSrc networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");function Ra(){var a=Pa[W],b=a.charAt(0).toUpperCase()+a.slice(1);Oa["set"+b]=function(b){return this.a.vjs_setProperty(a,b)}}
function Sa(a){Oa[a]=function(){return this.a.vjs_getProperty(a)}}var W;for(W=0;W<Pa.length;W++)Sa(Pa[W]),Ra();for(W=0;W<Qa.length;W++)Sa(Qa[W]);V.prototype.C={Gb:{"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"},ib:j,nb:j,ab:j,uc:!u.A.match("Firefox")};V.onReady=function(a){a=u.j(a);var b=a.player||a.parentNode.player,d=b.i;a.player=b;d.a=a;d.d("click",d.k);Na(d)};function Na(a){a.j().vjs_getProperty?ha(a):setTimeout(function(){Na(a)},50)}
V.onEvent=function(a,b){"play"!==b&&u.j(a).player.h(b)};V.onError=function(a,b){u.j(a).player.h("error");u.log("Flash Error",b,a)};
function Ma(a,b,d,e){var g="",p="",l="";b&&u.g.W(b,function(a,b){g+=a+"="+b+"&amp;"});d=u.g.t({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);u.g.W(d,function(a,b){p+='<param name="'+a+'" value="'+b+'" />'});e=u.g.t({data:a,width:"100%",height:"100%"},e);u.g.W(e,function(a,b){l+=a+'="'+b+'" '});return'<object type="application/x-shockwave-flash"'+l+">"+p+"</object>"};function X(a){a.$=a.$||[];return a.$}function Ta(a,b,d){for(var e=a.$,g=0,p=e.length,l,s;g<p;g++)l=e[g],l.id()===b?(l.show(),s=l):d&&(l.z()==d&&0<l.mode())&&l.disable();(b=s?s.z():d?d:j)&&a.h(b+"trackchange")}function Y(a,b){x.call(this,a,b);this.B=b.id||"vjs_"+b.kind+"_"+b.language+"_"+u.n++;this.kb=b.src;this.Bb=b["default"]||b.dflt;this.wc=b.title;this.qc=b.srclang;this.Ib=b.label;this.P=[];this.Ra=[];this.S=this.T=0;this.b.d("fullscreenchange",u.bind(this,this.xb))}t(Y,x);n=Y.prototype;n.z=k("q");
n.src=k("kb");n.xa=k("Bb");n.label=k("Ib");n.readyState=k("T");n.mode=k("S");n.xb=function(){this.a.style.fontSize=this.b.D?140*(screen.width/this.b.width())+"%":""};n.c=function(){return Y.e.c.call(this,"div",{className:"vjs-"+this.q+" vjs-text-track"})};n.show=function(){Ua(this);this.S=2;Y.e.show.call(this)};n.s=function(){Ua(this);this.S=1;Y.e.s.call(this)};
n.disable=function(){2==this.S&&this.s();this.b.m("timeupdate",u.bind(this,this.update,this.B));this.b.m("ended",u.bind(this,this.reset,this.B));this.reset();this.b.H.textTrackDisplay.removeChild(this);this.S=0};function Ua(a){0===a.T&&a.load();0===a.S&&(a.b.d("timeupdate",u.bind(a,a.update,a.B)),a.b.d("ended",u.bind(a,a.reset,a.B)),("captions"===a.q||"subtitles"===a.q)&&a.b.H.textTrackDisplay.J(a))}n.load=function(){0===this.T&&(this.T=1,u.get(this.kb,u.bind(this,this.Qb),u.bind(this,this.Ia)))};
n.Ia=function(a){this.error=a;this.T=3;this.h("error")};n.Qb=function(a){var b,d;a=a.split("\n");for(var e="",g=1,p=a.length;g<p;g++)if(e=u.trim(a[g])){-1==e.indexOf("--\x3e")?(b=e,e=u.trim(a[++g])):b=this.P.length;b={id:b,index:this.P.length};d=e.split(" --\x3e ");b.startTime=Va(d[0]);b.X=Va(d[1]);for(d=[];a[++g]&&(e=u.trim(a[g]));)d.push(e);b.text=d.join("<br/>");this.P.push(b)}this.T=2;this.h("loaded")};
function Va(a){var b=a.split(":");a=0;var d,e,g;3==b.length?(d=b[0],e=b[1],b=b[2]):(d=0,e=b[0],b=b[1]);b=b.split(/\s+/);b=b.splice(0,1)[0];b=b.split(/\.|,/);g=parseFloat(b[1]);b=b[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(b);g&&(a+=g/1E3);return a}
n.update=function(){if(0<this.P.length){var a=this.b.currentTime();if(this.Ma===c||a<this.Ma||this.ha<=a){var b=this.P,d=this.b.duration(),e=0,g=j,p=[],l,s,q,w;a>=this.ha||this.ha===c?w=this.za!==c?this.za:0:(g=f,w=this.Fa!==c?this.Fa:b.length-1);for(;;){q=b[w];if(q.X<=a)e=Math.max(e,q.X),q.ca&&(q.ca=j);else if(a<q.startTime){if(d=Math.min(d,q.startTime),q.ca&&(q.ca=j),!g)break}else g?(p.splice(0,0,q),s===c&&(s=w),l=w):(p.push(q),l===c&&(l=w),s=w),d=Math.min(d,q.X),e=Math.max(e,q.startTime),q.ca=
f;if(g)if(0===w)break;else w--;else if(w===b.length-1)break;else w++}this.Ra=p;this.ha=d;this.Ma=e;this.za=l;this.Fa=s;a=this.Ra;b="";d=0;for(e=a.length;d<e;d++)b+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.a.innerHTML=b;this.h("cuechange")}}};n.reset=function(){this.ha=0;this.Ma=this.b.duration();this.Fa=this.za=0};function Wa(a,b){Y.call(this,a,b)}t(Wa,Y);Wa.prototype.q="captions";function Xa(a,b){Y.call(this,a,b)}t(Xa,Y);Xa.prototype.q="subtitles";function Ya(a,b){Y.call(this,a,b)}
t(Ya,Y);Ya.prototype.q="chapters";function Za(a,b,d){x.call(this,a,b,d);if(a.f.tracks&&0<a.f.tracks.length){b=this.b;a=a.f.tracks;var e;for(d=0;d<a.length;d++){e=a[d];var g=b,p=e.kind,l=e.label,s=e.language,q=e;e=g.$=g.$||[];q=q||{};q.kind=p;q.label=l;q.language=s;p=u.L(p||"subtitles");g=new window.videojs[p+"Track"](g,q);e.push(g)}}}t(Za,x);Za.prototype.c=function(){return Za.e.c.call(this,"div",{className:"vjs-text-track-display"})};
function Z(a,b){var d=this.O=b.track;b.label=d.label();b.selected=d.xa();S.call(this,a,b);this.b.d(d.z()+"trackchange",u.bind(this,this.update))}t(Z,S);Z.prototype.k=function(){Z.e.k.call(this);Ta(this.b,this.O.B,this.O.z())};Z.prototype.update=function(){2==this.O.mode()?this.selected(f):this.selected(j)};function $a(a,b){b.track={z:function(){return b.kind},Rb:a,label:m("Off"),xa:m(j),mode:m(j)};Z.call(this,a,b)}t($a,Z);$a.prototype.k=function(){$a.e.k.call(this);Ta(this.b,this.O.B,this.O.z())};
$a.prototype.update=function(){for(var a=X(this.b),b=0,d=a.length,e,g=f;b<d;b++)e=a[b],e.z()==this.O.z()&&2==e.mode()&&(g=j);g?this.selected(f):this.selected(j)};function $(a,b){E.call(this,a,b);this.ga=this.wa();0===this.Y.length&&this.s();this.d("keyup",this.M);this.a.setAttribute("aria-haspopup",f);this.a.setAttribute("role","button")}t($,E);n=$.prototype;n.U=j;
n.wa=function(){var a=new R(this.b);a.j().appendChild(u.c("li",{className:"vjs-menu-title",innerHTML:u.L(this.q),bc:-1}));Ja(a,new $a(this.b,{kind:this.q}));this.Y=this.Va();for(var b=0;b<this.Y.length;b++)Ja(a,this.Y[b]);this.J(a);return a};n.Va=function(){for(var a=[],b,d=0;d<X(this.b).length;d++)b=X(this.b)[d],b.z()===this.q&&a.push(new Z(this.b,{track:b}));return a};n.r=function(){return this.className+" vjs-menu-button "+$.e.r.call(this)};n.ja=function(){};n.ia=function(){};
n.k=function(){this.F("mouseout",u.bind(this,function(){ia(this.ga);this.a.blur()}));this.U?ab(this):bb(this)};n.M=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.U?ab(this):bb(this);27==a.which&&(a.preventDefault(),this.U&&ab(this))};function bb(a){a.U=f;a.ga.fb();a.a.setAttribute("aria-pressed",f);a.a.children[1].children[0].focus()}function ab(a){a.U=j;ia(a.ga);a.a.setAttribute("aria-pressed",j)}
function cb(a,b){$.call(this,a,b);this.a.setAttribute("aria-label","Captions Menu")}t(cb,$);cb.prototype.q="captions";cb.prototype.K="Captions";cb.prototype.className="vjs-captions-button";function db(a,b){$.call(this,a,b);this.a.setAttribute("aria-label","Subtitles Menu")}t(db,$);db.prototype.q="subtitles";db.prototype.K="Subtitles";db.prototype.className="vjs-subtitles-button";function eb(a,b){$.call(this,a,b);this.a.setAttribute("aria-label","Chapters Menu")}t(eb,$);n=eb.prototype;n.q="chapters";
n.K="Chapters";n.className="vjs-chapters-button";n.Va=function(){for(var a=[],b,d=0;d<X(this.b).length;d++)b=X(this.b)[d],b.z()===this.q&&a.push(new Z(this.b,{track:b}));return a};
n.wa=function(){for(var a=X(this.b),b=0,d=a.length,e,g,p=this.Y=[];b<d;b++)if(e=a[b],e.z()==this.q&&e.xa()){if(2>e.readyState()){this.lc=e;e.d("loaded",u.bind(this,this.wa));return}g=e;break}a=this.ga=new R(this.b);a.a.appendChild(u.c("li",{className:"vjs-menu-title",innerHTML:u.L(this.q),bc:-1}));if(g){e=g.P;for(var l,b=0,d=e.length;b<d;b++)l=e[b],l=new fb(this.b,{track:g,cue:l}),p.push(l),a.J(l)}this.J(a);0<this.Y.length&&this.show();return a};
function fb(a,b){var d=this.O=b.track,e=this.cue=b.cue,g=a.currentTime();b.label=e.text;b.selected=e.startTime<=g&&g<e.X;S.call(this,a,b);d.d("cuechange",u.bind(this,this.update))}t(fb,S);fb.prototype.k=function(){fb.e.k.call(this);this.b.currentTime(this.cue.startTime);this.update(this.cue.startTime)};fb.prototype.update=function(){var a=this.cue,b=this.b.currentTime();a.startTime<=b&&b<a.X?this.selected(f):this.selected(j)};u.g.t(D.prototype.f.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});if(JSON&&"function"===JSON.parse)u.JSON=JSON;else{u.JSON={};var hb=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;u.JSON.parse=function(a,b){function d(a,e){var l,s,q=a[e];if(q&&"object"===typeof q)for(l in q)Object.prototype.hasOwnProperty.call(q,l)&&(s=d(q,l),s!==c?q[l]=s:delete q[l]);return b.call(a,e,q)}var e;a=String(a);hb.lastIndex=0;hb.test(a)&&(a=a.replace(hb,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?d({"":e},""):e;throw new SyntaxError("JSON.parse");}};u.ta=function(){var a,b,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((b=d[e])&&b.getAttribute)b.player===c&&(a=b.getAttribute("data-setup"),a!==h&&(a=u.JSON.parse(a||"{}"),ba(b,a)));else{u.Sa();break}else u.fc||u.Sa()};u.Sa=function(){setTimeout(u.ta,1)};u.F(window,"load",function(){u.fc=f});u.ta();u.Sb=function(a,b){v.prototype[a]=b};r("videojs",u);r("_V_",u);r("videojs.options",u.options);r("videojs.cache",u.V);r("videojs.Component",x);x.prototype.dispose=x.prototype.w;x.prototype.createEl=x.prototype.c;x.prototype.el=x.prototype.j;x.prototype.addChild=x.prototype.J;x.prototype.children=x.prototype.children;x.prototype.on=x.prototype.d;x.prototype.off=x.prototype.m;x.prototype.one=x.prototype.F;x.prototype.trigger=x.prototype.h;x.prototype.show=x.prototype.show;x.prototype.hide=x.prototype.s;x.prototype.width=x.prototype.width;
x.prototype.height=x.prototype.height;x.prototype.dimensions=x.prototype.Cb;r("videojs.Player",v);r("videojs.MediaLoader",xa);r("videojs.PosterImage",Ia);r("videojs.LoadingSpinner",J);r("videojs.BigPlayButton",I);r("videojs.ControlBar",D);r("videojs.TextTrackDisplay",Za);r("videojs.Control",C);r("videojs.ControlBar",D);r("videojs.Button",E);r("videojs.PlayButton",F);r("videojs.PauseButton",G);r("videojs.PlayToggle",ya);r("videojs.FullscreenToggle",H);r("videojs.BigPlayButton",I);
r("videojs.LoadingSpinner",J);r("videojs.CurrentTimeDisplay",K);r("videojs.DurationDisplay",L);r("videojs.TimeDivider",za);r("videojs.RemainingTimeDisplay",M);r("videojs.Slider",N);r("videojs.ProgressControl",O);r("videojs.SeekBar",P);r("videojs.LoadProgressBar",Ba);r("videojs.PlayProgressBar",Ca);r("videojs.SeekHandle",Da);r("videojs.VolumeControl",Ea);r("videojs.VolumeBar",Fa);r("videojs.VolumeLevel",Ga);r("videojs.VolumeHandle",Ha);r("videojs.MuteToggle",Q);r("videojs.PosterImage",Ia);
r("videojs.Menu",R);r("videojs.MenuItem",S);r("videojs.SubtitlesButton",db);r("videojs.CaptionsButton",cb);r("videojs.ChaptersButton",eb);r("videojs.MediaTechController",T);r("videojs.Html5",U);U.Events=La;U.isSupported=function(){return!!document.createElement("video").canPlayType};U.canPlaySource=function(a){return!!document.createElement("video").canPlayType(a.type)};U.prototype.setCurrentTime=U.prototype.Wb;U.prototype.setVolume=U.prototype.ac;U.prototype.setMuted=U.prototype.Zb;
U.prototype.setPreload=U.prototype.$b;U.prototype.setAutoplay=U.prototype.Vb;U.prototype.setLoop=U.prototype.Yb;r("videojs.Flash",V);
V.isSupported=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(b){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return 10<=a.split(",")[0]};V.canPlaySource=function(a){if(a.type in V.prototype.C.Gb)return"maybe"};
V.onReady=V.onReady;r("videojs.TextTrack",Y);Y.prototype.label=Y.prototype.label;r("videojs.CaptionsTrack",Wa);r("videojs.SubtitlesTrack",Xa);r("videojs.ChaptersTrack",Ya);r("videojs.autoSetup",u.ta);r("videojs.plugin",u.Sb);
